multiple pre-release changes
Multiple changes in the code for readability, continuity and overall
improvement

diff --git a/joblistCreator b/joblistCreator
--- a/joblistCreator
+++ b/joblistCreator
@@ -35,7 +35,7 @@ SCRIPTNAME="$(basename $0)"
 
 # Errors go to stderr
 err() {
-  echo "ERROR: $@ See --help" >&2
+  echo "ERROR: $@" >&2
 }
 # Create absolute 'real' paths (to be shure were to output is)
 absolutepath () {
diff --git a/slide2Tiles b/slide2Tiles
--- a/slide2Tiles
+++ b/slide2Tiles
@@ -30,24 +30,179 @@
 # Respect the Google Shell style guide.
 # http://google-styleguide.googlecode.com/svn/trunk/shell.xml
 
-
-
-
-
-
-
-
-# Settings
+# Variables
+SCRIPTNAME=$(basename $0)
+DESCRIPTIONSHORT="Cut virtual slides into tiles"
+DEPENDENCIES=("convert parallel")
+DEFAULTLAYER=3 # 3
+DEFAULTHEIGHT=2000
+DEFAULTWIDTH=2000
+TMPDIR="$(mktemp -d -t slide2Tiles_XXXXXXXXXXXX)"
 SLOTS=4
 MEMORYLIMIT="$((15 * $SLOTS))GB" # 15 GB per slot
 
-# output log
-echo "$(date) Running $0"
 
-# create tiles
-if [ -f $1 ]; then    
+# Errors go to stderr
+err() {
+  echo "ERROR: $@" >&2
+}
+
+# usage message
+usage() {
+cat <<- EOF
+usage:  $SCRIPTNAME [options] [path/]file
+        [--help]
+EOF
+}
+# help message
+helpMessage() {
+cat <<- EOF
+${SCRIPTNAME}: ${DESCRIPTIONSHORT}
+
+$(usage)
+
+options:
+  -f, --file[=FILE]         virtual slide to create tiles from
+  --layer[=INT]             force specific layer [$DEFAULTLAYER]
+  --height[=PIXELS]         tile height in pixels [$DEFAULTHEIGHT]
+  --width[=PIXELS]          tile width in pixels [$DEFAULTWIDTH]
+  
+  --help                    display this help and exit
+
+examples:
+  $SCRIPTNAME "file.tif"
+  $SCRIPTNAME  --file="file.tif"
+  find [path/] -name '*.tif' | parallel [path/]slideMask {} 
+  find [path/] -name '*.tif' -exec qsub [path/]slideMask {} \; 
+
+dependencies: $DEPENDENCIES
+
+Cut slides into tiles for further processing. Reasonable tile size is
+2000 by 2000 pixels (default).
+
+Report bugs to <b.g.l.nelissen@gmail.com>
+slideToolkit (C) 2014, B.G.L. Nelissen
+EOF
+}
+
+# Menu
+# Empty variables
+FILE=""
+LAYER=""
+# illegal option
+illegalOption() {
+cat <<- EOF
+$SCRIPTNAME: illegal option $1
+$(usage)
+EOF
+exit 1
+}
+# loop through options
+while :
+do
+  case $1 in
+    --help | -\?)
+      helpMessage
+      exit 0 ;;
+    -f | --file)
+      FILE=$2
+      shift 2 ;;
+    --file=*)
+      FILE=${1#*=}
+      shift ;;
+    --layer=*)
+      LAYER=${1#*=}
+      shift ;;
+    --height=*)
+      HEIGHT=${1#*=}
+      shift ;;
+    --width=*)
+      WIDTH=${1#*=}
+      shift ;;
+    --) # End of all options
+      shift
+      break ;;
+    -*)
+      illegalOption "$1"
+      shift ;;
+    *)  # no more options. Stop while loop
+      break ;;
+  esac
+done
+
+# DEFAULTS
+# set FILE default
+if [ "$FILE" != "" ]; then
+  FILE="$FILE"
+else
+  FILE="$1"
+fi
+# set LAYER default
+if [ "$LAYER" != "" ]; then
+  LAYER="$LAYER"
+else
+  LAYER="$DEFAULTLAYER"
+fi
+# set HEIGHT default
+if [ "$HEIGHT" != "" ]; then
+  HEIGHT="$HEIGHT"
+else
+  HEIGHT="$DEFAULTHEIGHT"
+fi
+# set WIDTH default
+if [ "$WIDTH" != "" ]; then
+  WIDTH="$WIDTH"
+else
+  WIDTH="$DEFAULTWIDTH"
+fi
+
+
+# requirements
+checkRequirements() {
+  if ! [[ -f "$FILE" ]] ; then
+    echo "No such file: $FILE">&2;
+    usage
+    exit 1
+  fi
+  regexnumeric='^[0-9]+$'
+  if ! [[ $LAYER =~ $regexnumeric ]] ; then
+    echo "Layer is not an integer: $LAYER">&2;
+    usage
+    exit 1
+  fi
+  if ! [[ $HEIGHT =~ $regexnumeric ]] ; then
+    echo "Height is not valid: $HEIGHT">&2;
+    usage
+    exit 1
+  fi
+  if ! [[ $WIDTH =~ $regexnumeric ]] ; then
+    echo "Width is not valid: $WIDTH">&2;
+    usage
+    exit 1
+  fi
+}
+
+# Dependencies
+checkDependencies(){
+  DEPENDENCIES="$DEPENDENCIES"
+  DEPS=""
+  for DEP in $DEPENDENCIES; do
+    if [[ 0 != $(command -v "$DEP" >/dev/null ;echo $?) ]]; then
+      DEPS=$(echo "$DEPS $DEP") # create `array` with unknown dependencies
+    fi
+  done
+  if [[ "" != $(echo "$DEPS" | perl -p -e 's/ //g') ]]; then
+    for d in $DEPS; do
+      echo "Missing dependency: \"$d\""
+    done
+    exit 1
+  fi
+}
+
+# actual program
+programOutput(){
     # set and get variables
-    S="$1" # input scan
+    S="$FILE" # input scan
     INPUTFILENAME="${S%.*}"             # full path without extension
     INPUTSCANEXT="${S##*.}"             # input scan extension only
     M="${INPUTFILENAME}.mask.png"       # input mask
@@ -55,32 +210,29 @@ if [ -f $1 ]; then
     SHORTNAME="$(basename $INPUTFILENAME)"
     FILENAMEMASK="${M##*/}"
     FOLDERINPUT=$(dirname "$S")         # input folder
-    FOLDERWORK="$TMPDIR"  # CAREFUL THIS FOLDER GETS DELETED! # CAREFUL WITH THIS MOTHERFUCKER
+    TMPDIR="$TMPDIR"                    # CAREFUL THIS FOLDER GETS DELETED! # CAREFUL WITH THIS MOTHERFUCKER
     FOLDEROUTPUT=$(dirname "$S")        # output directory
-    LAYER=3                             # layer 3 is 20x (for Roche scanner)
-    TILESWIDTH=2000
-    TILESHEIGHT=2000
-    buffer="${FOLDERWORK}/${SHORTNAME}.mpc"
+    LAYER="$LAYER"                             # layer 3 is 20x (for Roche scanner)
+    TILESWIDTH="$WIDTH"
+    TILESHEIGHT="$HEIGHT"
+    buffer="${TMPDIR}/${SHORTNAME}.mpc"
     STARTDATE=$(date)
-    
+      
     # all complete? Lets go
     if [[ -f "$S" && -f "$M" && "tif" == $INPUTSCANEXT ]] ; then
         width=$(identify -format "%w" "${S}[${LAYER}]")
         height=$(identify -format "%h" "${S}[${LAYER}]")
         dimensions=${width}x${height}
         echo "dimensions $dimensions"
-        
-        # empty FOLDERWORK
-        rm -rf ${FOLDERWORK}/* # CAREFUL WITH THIS MOTHERFUCKER
-        mkdir -p ${FOLDERWORK}
+        echo "tmpdir : $TMPDIR"
         echo "$(date)"
         echo "Start convert and create big buffer file..."
         convert -limit area ${MEMORYLIMIT} ${S}[${LAYER}] \( ${M} -fuzz 99% -transparent white -scale ${dimensions} -negate \) -composite -fuzz 3% -trim +repage -bordercolor white -border 30x30 +repage ${buffer}
         echo "$(date)"
         echo "Ended convert..."
         echo "Start convert to create bufferexample..."
-        # output for user so we know what was in the hpc file (contrain proportions within 2000x2000 pixels)
-        convert -limit area ${MEMORYLIMIT} ${buffer} -scale 2000x2000 ${INPUTFILENAME}.bufferexample.png
+        # output for user so we know what was in the hpc file
+        convert -limit area ${MEMORYLIMIT} ${buffer} -scale "$TILESWIDTH"x"$TILESHEIGHT" ${INPUTFILENAME}.bufferexample.png
         echo "$(date)"
         echo "Ended convert..."# create output directory with similar name as input file
         mkdir -v -p "$INPUTFILENAME" # create output directory
@@ -94,6 +246,8 @@ if [ -f $1 ]; then
         echo "Start creating tiles..."
         echo "width      $width"
         echo "height     $height"
+        echo "tile width $TILESWIDTH"
+        echo "tile height $TILESHEIGHT"
         echo "dimensions $dimensions"
         echo "limit_w    $limit_w"
         echo "limit_h    $limit_h"
@@ -146,14 +300,22 @@ if [ -f $1 ]; then
              done
          done
         echo "$(date)"
-        echo "Ended creating tiles..."        
+        echo "Ended creating tiles..."
+        echo "Remove tmp dir"       
         # $TMPDIR get automatically deleted after each job.
+        rm -rfv "$TMPDIR"
     else
-        echo "No such scan: $S"
-        echo "No such mask: $M"
+        err "No such scan: $S"
+        err "No such mask: $M"
+        usage
+        exit 1
     fi
     STOPDATE=$(date)
-    #  message user that slide is done
-    # /home/dhl_ec/bnelissen/bin/pushover.sh "${SHORTNAME} finished. Start ${STARTDATE}. Stop ${STOPDATE}"
-fi
-exit
+}
+
+# all check?
+checkRequirements
+checkDependencies
+
+# lets go!
+programOutput
diff --git a/slideDirectory b/slideDirectory
--- a/slideDirectory
+++ b/slideDirectory
@@ -34,9 +34,18 @@
 # to keep the things organized and to make future updates easier
 #
 # Variables
-SCRIPTNAME=$(basename $0)
+SCRIPTNAME="$(basename $0)"
 DESCRIPTIONSHORT="Move file into a similar named directory"
 
+# Errors go to stderr
+err() {
+  echo "ERROR: $@" >&2
+}
+# Create absolute 'real' paths (to be shure were to output is)
+absolutepath () {
+  p="$(echo $(cd $(dirname $1); pwd)/$(basename $1))"
+  echo "$p"
+}
 # usage message
 usage() {
 cat <<- EOF
@@ -111,7 +120,8 @@ fi
 # requirements
 checkRequirements() {
   if ! [[ -f "$FILE" ]] ; then
-    echo "No such file: $FILE" >&2;
+    err "No such file: $FILE"
+    usage
     exit 1
   fi
 }
@@ -127,11 +137,8 @@ programOutput(){
   mv "$FILE" "$FILEPATH"/
 }
 
-
-
 # all check?
 checkRequirements
 
 # lets go!
 programOutput
-
diff --git a/slideMask b/slideMask
--- a/slideMask
+++ b/slideMask
@@ -34,6 +34,10 @@
 SCRIPTNAME=$(basename $0)
 DESCRIPTIONSHORT="Create macro and mask from virtual slide"
 
+# Errors go to stderr
+err() {
+  echo "ERROR: $@" >&2
+}
 # usage message
 usage() {
 cat <<- EOF
@@ -56,6 +60,8 @@ options:
 examples:
   $SCRIPTNAME "file.tif"
   $SCRIPTNAME  --file="file.tif"
+  find [path/] -name '*.tif' | parallel [path/]slideMask {} 
+  find [path/] -name '*.tif' -exec qsub [path/]slideMask {} \; 
 
 Sometimes not all tissue on your virtual slide needs processing. You can
 mask parts of your image that you do not wat to process. This program
@@ -63,6 +69,7 @@ will automatically create a mask for you which you can later edit if
 needed. The slideToolkit only excludes real black (color #000000). Two
 new files will be created, one file.macro.png and one file.mask.png.
 Existing files will be overwritten.
+
 Report bugs to <b.g.l.nelissen@gmail.com>
 slideToolkit (C) 2014, B.G.L. Nelissen
 EOF
@@ -112,14 +119,14 @@ fi
 # requirements
 checkRequirements() {
   if ! [[ -f "$FILE" ]] ; then
-    echo "No such file: $FILE">&2;
+    err "No such file: $FILE"
     usage
     exit 1
   fi
 }
 
 # Dependencies
-function checkDependencies(){
+checkDependencies(){
   DEPENDENCIES=("convert")
   DEPS=""
   for DEP in $DEPENDENCIES; do
@@ -127,9 +134,9 @@ function checkDependencies(){
       DEPS=$(echo "$DEPS \"$DEP\"") # create `array` with unknown dependencies
     fi
   done
-  if [[ 0 != ${#DEPS[@]} ]]; then
-    for d in $DEPS; do
-      echo "Missing dependency: $d"
+  if [[ "" != "$DEPS" ]]; then
+    for d in "$DEPS"; do
+      err "Missing dependency: $d"
     done
     exit 1
   fi
@@ -138,38 +145,38 @@ function checkDependencies(){
 # actual program
 programOutput(){
   # set variables
-	LAYER=8
+  LAYER=8
   FILEFULL="$(echo $(cd $(dirname $FILE); pwd)/$(basename $FILE))" # full path $FULL
   BASENAME=$(basename "$FILEFULL")    # basename
   EXTENSION="${BASENAME##*.}"         # extension
   FILEPATH="${FILEFULL%.*}"           # full path, no extension
   FILENAME="${BASENAME%.*}"           # filename, no extension"
-	MASK="$FILEPATH.mask.png"
-	MACRO="$FILEPATH.macro.png"
-	
-	# create macro
-	convert $FILEFULL[$LAYER] -fuzz 1% -transparent "#ECECEC"  $MACRO
-	# create mask
-	# a fuzz of 3% works well, but fails on very light slides
-	# a fuzz of 2% is mightby to easy on the selection
-	# a fuzz of 2.5% is possible (but still to stringend on some slides)
-	#	 - add a border so blur works on the whole image
+  MASK="$FILEPATH.mask.png"
+  MACRO="$FILEPATH.macro.png"
+
+  # create macro
+  convert $FILEFULL[$LAYER] -fuzz 1% -transparent "#ECECEC"  $MACRO
+  # create mask
+  # a fuzz of 3% works well, but fails on very light slides
+  # a fuzz of 2% is mightby to easy on the selection
+  # a fuzz of 2.5% is possible (but still to stringend on some slides)
+  #	 - add a border so blur works on the whole image
   #	 - blur the image to fill small holes (blur is slow, but necessary)
   #	 - make all white transparent (background)
   #	 - remove the border
   #	 - create alpha and save file
-	convert $MACRO \( $MACRO \
-			-bordercolor white -border 100x100 \
-			-blur 40x40 \
-			-fuzz 2% -transparent white \
-			-crop +100+100 -crop -100-100 +repage \
-			-alpha extract -transparent white \) \
-		-flatten $MASK
+  convert $MACRO \( $MACRO \
+    -bordercolor white -border 100x100 \
+    -blur 40x40 \
+    -fuzz 2% -transparent white \
+    -crop +100+100 -crop -100-100 +repage \
+    -alpha extract -transparent white \) \
+    -flatten $MASK
 }
-
 # all check?
 checkRequirements
 checkDependencies 
 
 # lets go!
+# actual program
 programOutput
diff --git a/slideThumb b/slideThumb
--- a/slideThumb
+++ b/slideThumb
@@ -35,6 +35,10 @@
 # Variables
 SCRIPTNAME=$(basename $0)
 DESCRIPTIONSHORT="Extract thumbnail from virtual slide"
+DEPENDENCIES=("convert parallel perl")
+
+# DEBUG setting, remove before going live
+# set -o verbose
 
 # usage message
 usage() {
@@ -52,13 +56,18 @@ $(usage)
 
 options:
   -f, --file[=FILE]         extract the thumbnail from this virtual slide
-  -l, --layer[=INT]         force specific layer extraction by layer id
+  -l, --layer[=INT]         force specific layer by layer id
 
   --help                    display this help and exit
 
 examples:
   $SCRIPTNAME "file.tif"
   $SCRIPTNAME  --file="file.tif"
+
+multiple files at once:
+  find -L ./  -name '*.tif' | parallel $SCRIPTNAME {}
+
+dependencies: $DEPENDENCIES
 
 Most virtual slides contain a an overview image from each slide, aka
 thumbnail. This script does a good job of extracting the correct layer,
@@ -68,6 +77,7 @@ Report bugs to <b.g.l.nelissen@gmail.com>
 slideToolkit (C) 2014, B.G.L. Nelissen
 EOF
 }
+
 # Menu
 # Empty variables
 FILE=""
@@ -130,8 +140,8 @@ checkRequirements() {
     usage
     exit 1
   fi
-  regex='^[0-9]+$'
-  if ! [[ $LAYER =~ $regex ]] ; then
+  regexnumeric='^[0-9]+$'
+  if ! [[ $LAYER =~ $regexnumeric ]] ; then
     echo "Layer is not an integer: $LAYER">&2;
     usage
     exit 1
@@ -139,17 +149,17 @@ checkRequirements() {
 }
 
 # Dependencies
-function checkDependencies(){
-  DEPENDENCIES=("convert")
+checkDependencies(){
+  DEPENDENCIES="$DEPENDENCIES"
   DEPS=""
   for DEP in $DEPENDENCIES; do
     if [[ 0 != $(command -v "$DEP" >/dev/null ;echo $?) ]]; then
-      DEPS=$(echo "$DEPS \"$DEP\"") # create `array` with unknown dependencies
+      DEPS=$(echo "$DEPS $DEP") # create `array` with unknown dependencies
     fi
   done
-  if [[ 0 != ${#DEPS[@]} ]]; then
+  if [[ "" != $(echo "$DEPS" | perl -p -e 's/ //g') ]]; then
     for d in $DEPS; do
-      echo "Missing dependency: $d"
+      echo "Missing dependency: \"$d\""
     done
     exit 1
   fi
@@ -165,7 +175,7 @@ programOutput(){
   FILENAME="${BASENAME%.*}"           # filename, no extension"
 	
 	# get the thumb
-	convert "$FILEFULL"[$LAYER] "$FILEPATH"."$LAYER".thumb.png;
+	convert "$FILEFULL"[$LAYER] "$FILEPATH"."$LAYER".thumb.png
 }
 
 # all check?
