Merge branch 'version-flag-0.1-beta'

diff --git a/slide2Tiles b/slide2Tiles
--- a/slide2Tiles
+++ b/slide2Tiles
@@ -28,7 +28,7 @@
 # Variables
 SCRIPTNAME="$(basename $0)"
 DESCRIPTIONSHORT="Cut whole virtual slide into tiles"
-DEPENDENCIES=("convert" "identify" "parallel" "perl"  "openslide-write-png") # must exist in PATH
+DEPENDENCIES=("convert" "identify" "perl"  "openslide-write-png") # must exist in PATH
 SUPPORTED_FORMATS=("TIFF" "Aperio" "Hamamatsu" "iScan" "iScanHT" "Leica")
 DEFAULT_MASKSUFFIX=".mask.png"
 DEFAULT_LAYER=3 # 3
@@ -61,6 +61,33 @@ $SCRIPTNAME --help for more information.
 EOF
 }
 
+# version info
+version() {
+cat << EOF
+slideToolkit 0.1 beta
+($SCRIPTNAME is part of the slideToolkit)
+
+The MIT License (MIT) <http://opensource.org/licenses/MIT>
+Copyright (c) 2014, UMC Utrecht, Bas Nelissen
+
+Permission is hereby granted, free of charge, to any person obtaining a
+copy of this software and associated documentation files (the
+"Software"), to deal in the Software without restriction, including
+without limitation the rights to use, copy, modify, merge, publish,
+distribute, sublicense, and/or sell copies of the Software, and to
+permit persons to whom the Software is furnished to do so, subject to
+the following conditions:
+
+The above copyright notice and this permission notice shall be included
+in all copies or substantial portions of the Software.
+
+There is NO WARRANTY, to the extent permitted by law.
+
+Written by Bas Nelissen.
+EOF
+}
+
+
 # help message
 helpMessage() {
 cat <<- EOF
@@ -79,7 +106,7 @@ options:
   [--overlap] <pixels>      image overlap of adjacent tiles ["$DEFAULT_OVERLAP"]
   [--keep-empty]            do not delete empty tiles when found
   [--outputsuffix] <text>   output directory suffix
-  [--ignore-dependencies]   ignores all dependencies
+  [--ignore-dependencies]   ignores all dependencies, but gives warning
   [--verbose]               verbose output (for debugging)
   
   --help                    display this help
@@ -152,6 +179,9 @@ do
   case $1 in
     --help | -\?)
       helpMessage
+      exit 0 ;;
+    --version )
+      version
       exit 0 ;;
     -h )
       usage
@@ -265,7 +295,7 @@ if [[ "$KEEPEMPTYTILES" =~ (true|TRUE|YES|yes) ]] ; then
 else
   KEEPEMPTYTILES=false
 fi
-# set IGNOREDEPENDENCIES  (this if statement does nothing, as it is set to set in Menu)
+# set IGNOREDEPENDENCIES
 if [[ "$IGNOREDEPENDENCIES" =~ (true|TRUE|YES|yes) ]] ; then
   IGNOREDEPENDENCIES=true
 else
@@ -361,9 +391,14 @@ checkDependencies(){
     fi
   done
   if [[ "$DEPS_FAIL" > 0 ]]; then
-    err "Fix missing dependencies (${DEPS_FAIL})"
-    usage
-    exit 1
+    # only warning when --ignore-dependencies is set.
+    if [[ "$IGNOREDEPENDENCIES" == "true" ]]; then
+      err "Ignoring missing dependencies (${DEPS_FAIL}), continue..."
+    else
+      err "Fix missing dependencies (${DEPS_FAIL}), exit."
+      usage
+      exit 1
+    fi
   fi
 }
 
@@ -508,9 +543,7 @@ programOutput(){
 
 # all check?
 checkRequirements
-if ! [[ "$IGNOREDEPENDENCIES" == "true" ]]; then
-  checkDependencies
-fi
+checkDependencies
 
 # lets go!
 programOutput
diff --git a/slideConvert b/slideConvert
--- a/slideConvert
+++ b/slideConvert
@@ -46,6 +46,32 @@ $SCRIPTNAME --help for more information.
 EOF
 }
 
+# version info
+version() {
+cat << EOF
+slideToolkit 0.1 beta
+($SCRIPTNAME is part of the slideToolkit)
+
+The MIT License (MIT) <http://opensource.org/licenses/MIT>
+Copyright (c) 2014, UMC Utrecht, Bas Nelissen
+
+Permission is hereby granted, free of charge, to any person obtaining a
+copy of this software and associated documentation files (the
+"Software"), to deal in the Software without restriction, including
+without limitation the rights to use, copy, modify, merge, publish,
+distribute, sublicense, and/or sell copies of the Software, and to
+permit persons to whom the Software is furnished to do so, subject to
+the following conditions:
+
+The above copyright notice and this permission notice shall be included
+in all copies or substantial portions of the Software.
+
+There is NO WARRANTY, to the extent permitted by law.
+
+Written by Bas Nelissen.
+EOF
+}
+
 # help message
 helpMessage() {
 cat <<- EOF
@@ -58,6 +84,7 @@ options:
   -f, --file <filename>           Digital slide to convert to $DEFAULT_OUTPUTFORMAT
   
   [--bfconvert-args] <arguments>  bfconvert arguments ["$DEFAULT_BFCONVERTARGS"]
+  [--ignore-dependencies]         ignores all dependencies, but gives warning
 
   --help                    display this help
 
@@ -100,6 +127,9 @@ do
     --help | -\?)
       helpMessage
       exit 0 ;;
+    --version )
+      version
+      exit 0 ;;
     -f | --file)
       FILE=$2
       shift 2 ;;
@@ -111,6 +141,9 @@ do
       shift 2 ;;
     --bfconvert-args=*)
       BFCONVERTARGS=${1#*=}
+      shift ;;
+     --ignore-dependencies)
+      IGNOREDEPENDENCIES=TRUE
       shift ;;
     --) # End of all options
       shift
@@ -135,6 +168,12 @@ if [ "$BFCONVERTARGS" != "" ]; then
 else
   BFCONVERTARGS="$DEFAULT_BFCONVERTARGS"
 fi
+# set IGNOREDEPENDENCIES
+if [[ "$IGNOREDEPENDENCIES" =~ (true|TRUE|YES|yes) ]] ; then
+  IGNOREDEPENDENCIES=true
+else
+  IGNOREDEPENDENCIES=false
+fi
 
 # requirements
 checkRequirements() {
@@ -156,12 +195,16 @@ checkDependencies(){
     fi
   done
   if [[ "$DEPS_FAIL" > 0 ]]; then
-    err "Fix missing dependencies (${DEPS_FAIL})"
-    usage
-    exit 1
+    # only warning when --ignore-dependencies is set.
+    if [[ "$IGNOREDEPENDENCIES" == "true" ]]; then
+      err "Ignoring missing dependencies (${DEPS_FAIL}), continue..."
+    else
+      err "Fix missing dependencies (${DEPS_FAIL}), exit."
+      usage
+      exit 1
+    fi
   fi
 }
-
 # actual program
 programOutput(){
   FILEFULL="$(echo "$(cd "$(dirname "$FILE")"; pwd)"/"$(basename "$FILE")")" # full path $FULL
diff --git a/slideDirectory b/slideDirectory
--- a/slideDirectory
+++ b/slideDirectory
@@ -28,7 +28,7 @@
 # Variables
 SCRIPTNAME="$(basename $0)"
 DESCRIPTIONSHORT="Create a staging directorie per slide"
-DEPENDENCIES=("parallel")
+DEPENDENCIES=()
 
 # Errors go to stderr
 err() {
@@ -42,6 +42,33 @@ $SCRIPTNAME --help for more information.
 EOF
 }
 
+# version info
+version() {
+cat << EOF
+slideToolkit 0.1 beta
+($SCRIPTNAME is part of the slideToolkit)
+
+The MIT License (MIT) <http://opensource.org/licenses/MIT>
+Copyright (c) 2014, UMC Utrecht, Bas Nelissen
+
+Permission is hereby granted, free of charge, to any person obtaining a
+copy of this software and associated documentation files (the
+"Software"), to deal in the Software without restriction, including
+without limitation the rights to use, copy, modify, merge, publish,
+distribute, sublicense, and/or sell copies of the Software, and to
+permit persons to whom the Software is furnished to do so, subject to
+the following conditions:
+
+The above copyright notice and this permission notice shall be included
+in all copies or substantial portions of the Software.
+
+There is NO WARRANTY, to the extent permitted by law.
+
+Written by Bas Nelissen.
+EOF
+}
+
+
 # help message
 helpMessage() {
 cat <<- EOF
@@ -52,6 +79,8 @@ usage:
 
 options:
   -f, --file <filename>     Move file into a similar named directory 
+
+  [--ignore-dependencies]   ignores all dependencies, but gives warning
 
   --help                    display this help
 
@@ -92,11 +121,17 @@ do
     --help | -\?)
       helpMessage
       exit 0 ;;
+    --version )
+      version
+      exit 0 ;;
     -f | --file)
       FILE=$2
       shift 2 ;;
     --file=*)
       FILE=${1#*=}
+      shift ;;
+     --ignore-dependencies)
+      IGNOREDEPENDENCIES=TRUE
       shift ;;
     --) # End of all options
       shift
@@ -114,6 +149,12 @@ if [ "$FILE" != "" ]; then
   FILE="$FILE"
 else
   FILE="$1"
+fi
+# set IGNOREDEPENDENCIES
+if [[ "$IGNOREDEPENDENCIES" =~ (true|TRUE|YES|yes) ]] ; then
+  IGNOREDEPENDENCIES=true
+else
+  IGNOREDEPENDENCIES=false
 fi
 
 # requirements
@@ -136,11 +177,17 @@ checkDependencies(){
     fi
   done
   if [[ "$DEPS_FAIL" > 0 ]]; then
-    err "Fix missing dependencies (${DEPS_FAIL})"
-    usage
-    exit 1
+    # only warning when --ignore-dependencies is set.
+    if [[ "$IGNOREDEPENDENCIES" == "true" ]]; then
+      err "Ignoring missing dependencies (${DEPS_FAIL}), continue..."
+    else
+      err "Fix missing dependencies (${DEPS_FAIL}), exit."
+      usage
+      exit 1
+    fi
   fi
 }
+
 # actual program
 programOutput(){
   FILEFULL="$(echo "$(cd "$(dirname "$FILE")"; pwd)"/"$(basename "$FILE")")" # full path $FULL
diff --git a/slideMask b/slideMask
--- a/slideMask
+++ b/slideMask
@@ -28,7 +28,7 @@
 # Variables
 SCRIPTNAME=$(basename $0)
 DESCRIPTIONSHORT="Create scaled mask and macro from a virtual slide"
-DEPENDENCIES=("convert" "parallel")
+DEPENDENCIES=("convert")
 SUPPORTED_FORMATS=("TIFF" "Aperio" "Hamamatsu" "iScan" "iScanHT" "Leica")
 DEFAULT_MASKSUFFIX=".mask"
 DEFAULT_MACROSUFFIX=".macro"
@@ -48,6 +48,33 @@ $SCRIPTNAME --help for more information.
 EOF
 }
 
+# version info
+version() {
+cat << EOF
+slideToolkit 0.1 beta
+($SCRIPTNAME is part of the slideToolkit)
+
+The MIT License (MIT) <http://opensource.org/licenses/MIT>
+Copyright (c) 2014, UMC Utrecht, Bas Nelissen
+
+Permission is hereby granted, free of charge, to any person obtaining a
+copy of this software and associated documentation files (the
+"Software"), to deal in the Software without restriction, including
+without limitation the rights to use, copy, modify, merge, publish,
+distribute, sublicense, and/or sell copies of the Software, and to
+permit persons to whom the Software is furnished to do so, subject to
+the following conditions:
+
+The above copyright notice and this permission notice shall be included
+in all copies or substantial portions of the Software.
+
+There is NO WARRANTY, to the extent permitted by law.
+
+Written by Bas Nelissen.
+EOF
+}
+
+
 # help message
 helpMessage() {
 cat <<- EOF
@@ -63,6 +90,7 @@ options:
   [--macrosuffix] <text>        macro suffix ["$DEFAULT_MACROSUFFIX"]
   [-l, --layer] <integer>       force specific layer by layer id
   [--mask-args] <arguments>     mask arguments (imageMagick) ["$DEFAULT_MASKARGS"]
+  [--ignore-dependencies]       ignores all dependencies, but gives warning
   
   --help                        display this help
 
@@ -128,6 +156,9 @@ do
     --help | -\?)
       helpMessage
       exit 0 ;;
+    --version )
+      version
+      exit 0 ;;
     -f | --file)
       FILE=$2
       shift 2 ;;
@@ -157,6 +188,9 @@ do
       shift 2 ;;
     --macrosuffix=*)
       MACROSUFFIX=${1#*=}
+      shift ;;
+     --ignore-dependencies)
+      IGNOREDEPENDENCIES=TRUE
       shift ;;
     --) # End of all options
       shift
@@ -193,6 +227,12 @@ if [ "$MACROSUFFIX" != "" ]; then
 else
   MACROSUFFIX="$DEFAULT_MACROSUFFIX"
 fi
+# set IGNOREDEPENDENCIES
+if [[ "$IGNOREDEPENDENCIES" =~ (true|TRUE|YES|yes) ]] ; then
+  IGNOREDEPENDENCIES=true
+else
+  IGNOREDEPENDENCIES=false
+fi
 
 # requirements
 checkRequirements() {
@@ -214,12 +254,16 @@ checkDependencies(){
     fi
   done
   if [[ "$DEPS_FAIL" > 0 ]]; then
-    err "Fix missing dependencies (${DEPS_FAIL})"
-    usage
-    exit 1
+    # only warning when --ignore-dependencies is set.
+    if [[ "$IGNOREDEPENDENCIES" == "true" ]]; then
+      err "Ignoring missing dependencies (${DEPS_FAIL}), continue..."
+    else
+      err "Fix missing dependencies (${DEPS_FAIL}), exit."
+      usage
+      exit 1
+    fi
   fi
 }
-
 # get mask function for each type of scanner
 getMacro(){
   # get thumb by layer id
diff --git a/slideRename b/slideRename
--- a/slideRename
+++ b/slideRename
@@ -28,7 +28,7 @@
 # Variables
 SCRIPTNAME=$(basename $0)
 DESCRIPTIONSHORT="Batch rename slides"
-DEPENDENCIES=("awk" "convert" "dmtxread" "grep" "identify" "display" "parallel" "perl" "tiffinfo" "wmctrl" "zbarimg")
+DEPENDENCIES=("awk" "convert" "dmtxread" "grep" "identify" "display" "perl" "tiffinfo" "wmctrl" "zbarimg")
 SUPPORTED_FORMATS=("Generic-TIFF" "Aperio" "Hamamatsu" "iScan" "iScanHT" "Leica")
 DEFAULT_RESIZE="512x1024"
 DEFAULT_OUTPUT_PREFIX="" # empty by default
@@ -74,6 +74,33 @@ $SCRIPTNAME --help for more information.
 EOF
 }
 
+# version info
+version() {
+cat << EOF
+slideToolkit 0.1 beta
+($SCRIPTNAME is part of the slideToolkit)
+
+The MIT License (MIT) <http://opensource.org/licenses/MIT>
+Copyright (c) 2014, UMC Utrecht, Bas Nelissen
+
+Permission is hereby granted, free of charge, to any person obtaining a
+copy of this software and associated documentation files (the
+"Software"), to deal in the Software without restriction, including
+without limitation the rights to use, copy, modify, merge, publish,
+distribute, sublicense, and/or sell copies of the Software, and to
+permit persons to whom the Software is furnished to do so, subject to
+the following conditions:
+
+The above copyright notice and this permission notice shall be included
+in all copies or substantial portions of the Software.
+
+There is NO WARRANTY, to the extent permitted by law.
+
+Written by Bas Nelissen.
+EOF
+}
+
+
 # help message
 helpMessage() {
 cat <<- EOF
@@ -95,6 +122,7 @@ options:
   [--convert-args]='<arguments>'  convert arguments ('=' sign and 'quotes' required)
   [--preview im|osx|none]         display preview miniature (imageMagick, OS X Preview.app, none)
   [--wmctrl-timeout] <seconds>    window switching timeout ["$DEFAULT_WMCTRL_TIMEOUT"](see description)
+  [--ignore-dependencies]         ignores all dependencies, but gives warning
 
   --help                          display this help
 
@@ -164,6 +192,9 @@ do
     --help | -\?)
       helpMessage
       exit 0 ;;
+    --version )
+      version
+      exit 0 ;;
     -f | --file)
       FILE=$2
       shift 2 ;;
@@ -227,6 +258,9 @@ do
     --barcode)
       BARCODE=$2
       shift 2 ;;
+     --ignore-dependencies)
+      IGNOREDEPENDENCIES=TRUE
+      shift ;;
     --) # End of all options
       shift
       break ;;
@@ -273,6 +307,12 @@ if [ "$WMCTRL_TIMEOUT" != "" ]; then
   WMCTRL_TIMEOUT="$WMCTRL_TIMEOUT"
 else
   WMCTRL_TIMEOUT="$DEFAULT_WMCTRL_TIMEOUT"
+fi
+# set IGNOREDEPENDENCIES
+if [[ "$IGNOREDEPENDENCIES" =~ (true|TRUE|YES|yes) ]] ; then
+  IGNOREDEPENDENCIES=true
+else
+  IGNOREDEPENDENCIES=false
 fi
 
 # requirements
@@ -321,12 +361,16 @@ checkDependencies(){
     fi
   done
   if [[ "$DEPS_FAIL" > 0 ]]; then
-    err "Fix missing dependencies (${DEPS_FAIL})"
-    usage
-    exit 1
+    # only warning when --ignore-dependencies is set.
+    if [[ "$IGNOREDEPENDENCIES" == "true" ]]; then
+      err "Ignoring missing dependencies (${DEPS_FAIL}), continue..."
+    else
+      err "Fix missing dependencies (${DEPS_FAIL}), exit."
+      usage
+      exit 1
+    fi
   fi
 }
-
 # show thumbs per scanner type (-filter box is best for resizing and text)
 getThumb(){
   # get thumb by layer id
diff --git a/slideSQLheader b/slideSQLheader
--- a/slideSQLheader
+++ b/slideSQLheader
@@ -38,6 +38,33 @@ $SCRIPTNAME --help for more information.
 EOF
 }
 
+# version info
+version() {
+cat << EOF
+slideToolkit 0.1 beta
+($SCRIPTNAME is part of the slideToolkit)
+
+The MIT License (MIT) <http://opensource.org/licenses/MIT>
+Copyright (c) 2014, UMC Utrecht, Bas Nelissen
+
+Permission is hereby granted, free of charge, to any person obtaining a
+copy of this software and associated documentation files (the
+"Software"), to deal in the Software without restriction, including
+without limitation the rights to use, copy, modify, merge, publish,
+distribute, sublicense, and/or sell copies of the Software, and to
+permit persons to whom the Software is furnished to do so, subject to
+the following conditions:
+
+The above copyright notice and this permission notice shall be included
+in all copies or substantial portions of the Software.
+
+There is NO WARRANTY, to the extent permitted by law.
+
+Written by Bas Nelissen.
+EOF
+}
+
+
 # Errors go to stderr
 err() {
   echo "${SCRIPTNAME} ERROR: $@" >&2
@@ -55,6 +82,7 @@ options:
   -f, --file <filename>     "SQL_SETUP.SQL" file 
   
   [--add-head] <filename>   "file.csv" file 
+  [--ignore-dependencies]   ignores all dependencies, but gives warning
 
   --help                    display this help
 
@@ -96,6 +124,9 @@ do
     --help | -\?)
       helpMessage
       exit 0 ;;
+    --version )
+      version
+      exit 0 ;;
     -f | --file)
       FILE=$2
       shift 2 ;;
@@ -107,6 +138,9 @@ do
       shift 2 ;;
     --add-head=*)
       ADDHEAD=${1#*=}
+      shift ;;
+     --ignore-dependencies)
+      IGNOREDEPENDENCIES=TRUE
       shift ;;
     --) # End of all options
       shift
@@ -125,6 +159,12 @@ if [ "$FILE" != "" ]; then
 else
   FILE="$1"
 fi
+# set IGNOREDEPENDENCIES
+if [[ "$IGNOREDEPENDENCIES" =~ (true|TRUE|YES|yes) ]] ; then
+  IGNOREDEPENDENCIES=true
+else
+  IGNOREDEPENDENCIES=false
+fi
 
 #requirements
 checkRequirements() {
@@ -139,6 +179,28 @@ checkRequirements() {
       usage
       exit 1
     fi  
+  fi
+}
+
+# Dependencies
+checkDependencies(){
+  DEPS=""
+  DEPS_FAIL="0"
+  for DEP in ${DEPENDENCIES[@]}; do
+    if [[ 0 != "$(command -v "$DEP" >/dev/null ;echo "$?")" ]]; then
+       err "Missing dependency: $DEP"
+       DEPS_FAIL=$(($DEPS_FAIL + 1))
+    fi
+  done
+  if [[ "$DEPS_FAIL" > 0 ]]; then
+    # only warning when --ignore-dependencies is set.
+    if [[ "$IGNOREDEPENDENCIES" == "true" ]]; then
+      err "Ignoring missing dependencies (${DEPS_FAIL}), continue..."
+    else
+      err "Fix missing dependencies (${DEPS_FAIL}), exit."
+      usage
+      exit 1
+    fi
   fi
 }
 
@@ -162,6 +224,7 @@ programOutput(){
 }
 #all check?
 checkRequirements
+checkDependencies
 
 #lets go!
 programOutput
diff --git a/slideThumb b/slideThumb
--- a/slideThumb
+++ b/slideThumb
@@ -28,7 +28,7 @@
 # Variables
 SCRIPTNAME=$(basename $0)
 DESCRIPTIONSHORT="Create slide thumbnail, including label"
-DEPENDENCIES=("convert" "parallel" "perl")
+DEPENDENCIES=("convert" "perl")
 SUPPORTED_FORMATS=("Generic-TIFF" "Aperio" "Hamamatsu" "iScan" "iScanHT" "Leica")
 DEFAULT_OUTPUT_SUFFIX=".thumb"
 DEFAULT_OUTPUT_EXTENSION="png"
@@ -50,6 +50,33 @@ $SCRIPTNAME --help for more information.
 EOF
 }
 
+# version info
+version() {
+cat << EOF
+slideToolkit 0.1 beta
+($SCRIPTNAME is part of the slideToolkit)
+
+The MIT License (MIT) <http://opensource.org/licenses/MIT>
+Copyright (c) 2014, UMC Utrecht, Bas Nelissen
+
+Permission is hereby granted, free of charge, to any person obtaining a
+copy of this software and associated documentation files (the
+"Software"), to deal in the Software without restriction, including
+without limitation the rights to use, copy, modify, merge, publish,
+distribute, sublicense, and/or sell copies of the Software, and to
+permit persons to whom the Software is furnished to do so, subject to
+the following conditions:
+
+The above copyright notice and this permission notice shall be included
+in all copies or substantial portions of the Software.
+
+There is NO WARRANTY, to the extent permitted by law.
+
+Written by Bas Nelissen.
+EOF
+}
+
+
 # help message
 helpMessage() {
 cat <<- EOF
@@ -66,6 +93,7 @@ options:
   [--extension] <text>        thumbnail output extension ["$DEFAULT_OUTPUT_EXTENSION"]
   [--output-dir] <path>       path to output directory
   [--resize] <widthxheight>   maximum output dimentions ["$DEFAULT_RESIZE"]
+  [--ignore-dependencies]     ignores all dependencies, but gives warning
   
   --help                      display this help
 
@@ -124,6 +152,9 @@ do
     --help | -\?)
       helpMessage
       exit 0 ;;
+    --version )
+      version
+      exit 0 ;;
     --h)
       usage
       exit 0 ;;
@@ -162,6 +193,9 @@ do
       shift 2;;
     --output-dir=*)
       OUTPUT_DIRECTORY=${1#*=}
+      shift ;;
+     --ignore-dependencies)
+      IGNOREDEPENDENCIES=TRUE
       shift ;;
     --) # End of all options
       shift
@@ -205,6 +239,13 @@ if [ "$RESIZE" != "" ]; then
 else
   RESIZE="$DEFAULT_RESIZE"
 fi
+# set IGNOREDEPENDENCIES  (this if statement does nothing, as it is set to set in Menu)
+if [[ "$IGNOREDEPENDENCIES" =~ (true|TRUE|YES|yes) ]] ; then
+  IGNOREDEPENDENCIES=true
+else
+  IGNOREDEPENDENCIES=false
+fi
+
 # requirements
 checkRequirements() {
   if ! [[ -f "$FILE" ]] ; then
@@ -225,12 +266,16 @@ checkDependencies(){
     fi
   done
   if [[ "$DEPS_FAIL" > 0 ]]; then
-    err "Fix missing dependencies (${DEPS_FAIL})"
-    usage
-    exit 1
+    # only warning when --ignore-dependencies is set.
+    if [[ "$IGNOREDEPENDENCIES" == "true" ]]; then
+      err "Ignoring missing dependencies (${DEPS_FAIL}), continue..."
+    else
+      err "Fix missing dependencies (${DEPS_FAIL}), exit."
+      usage
+      exit 1
+    fi
   fi
 }
-
 # get thumb for each scanner type
 getThumb(){
   # get thumb by layer id
