added slide checker for logs and error files.

diff --git a/slideJobChecker b/slideJobChecker
--- a/slideJobChecker
+++ b/slideJobChecker
@@ -58,6 +58,13 @@ function echoerrorflashnooption {
     echo -e "${YELLOW}${BOLD}${FLASHING}${1}${NONE}"
 }
 
+function echosucces { 
+    echo -e "${YELLOW}${1}${NONE}"
+}
+function importantnote { 
+    echo -e "${CYAN}${1}${NONE}"
+}
+
 ### MESSAGE FUNCTIONS
 script_copyright_message() {
 	echo ""
@@ -84,87 +91,138 @@ script_copyright_message() {
 	echo "+ Reference: http://opensource.org.                                                                     +"
 	echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 }
-
 script_arguments_error() {
 	echoerror "$1" # ERROR MESSAGE
 	echoerror "- Argument #1  -- name of the stain as it appears in the filenames, e.g. FIBRIN."
+	echoerror "- Argument #2  -- path_to working directory, i.e. where all the image-subdirectories are."
+	echoerror "- Argument #3  -- analysis step to be checked, i.e. should contain the start of the error file: [slidemask, slide2tiles, slidenormalize, slidecellprofiler, slidewrapup]."
+	echoerror "- Argument #4  -- Unique label. A string-number combination (no spaces) for reference to the analysis run. [OPTIONAL]"
 	echoerror ""
-	echoerror "An example command would be: slideQuantify_tiling [arg1: STAIN] "
+	echoerror "An example command would be: slideJobChecker [arg1: STAIN] [arg2: path_to_working_directory] [arg3: analysis step]"
 	echoerror ""
+	echoerror "Please note that this command should be run within the working directory (Argument #2)."
+	echoerror ""
+	echoerror "NOTE: Currently only works for slide2tiles-error-files. Should be expanded to other error-files too."
 	echoerror "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
-	# The wrong arguments are passed, so we'll exit the script now!
-	exit 1
+  	# The wrong arguments are passed, so we'll exit the script now!
+  	exit 1
 }
 
 echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
-echobold "                          slideQuantify: Tiling"
+echobold "                               slideJobChecker"
 echo ""
 echoitalic "* Written by  : Sander W. van der Laan; Tim Bezemer; Tim van de Kerkhof"
 echoitalic "                Yipei Song"
 echoitalic "* E-mail      : s.w.vanderlaan-2@umcutrecht.nl"
-echoitalic "* Last update : 2021-09-02"
-echoitalic "* Version     : 2.0.2"
+echoitalic "* Last update : 2021-09-07"
+echoitalic "* Version     : 1.0.0"
 echo ""
-echoitalic "* Description : This script will start the tiling of images for slideToolKit"
-echoitalic "                analyses."
-echoitalic "                This is SLURM based."
+echoitalic "* Description : This script will check the contents of error files for a "
+echoitalic "                given project directory. "
+# echoitalic "                This is SLURM based."
 echo ""
 echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 
 echo ""
 ### REQUIRED | GENERALS	
-# STAIN="$1" # Depends on arg1
+STAIN="$1" # Depends on arg1
+PROJECTDIR="$2" # Depends on arg2
+STEP="$3"
+
+### OPTIONAL | GENERALS	 
+### https://stackoverflow.com/questions/9332802/how-to-write-a-bash-script-that-takes-optional-input-arguments
+UNIQUE_LABEL=${4-V1} # Depends on arg9
+# BATCH_SIZE=${10-5000} # Depends on arg10
+# RANDOM_SAMPLE=${11-50} # Depends on arg11
+
+QJOB_MEM_SLIDEMASK="100G"
+QJOB_TIME_SLIDEMASK="02:30:00"
+
+QJOB_MEM_SLIDE2TILES="150G"
+QJOB_TIME_SLIDE2TILES="04:30:00"
+
+QJOB_MEM_SLIDENORM="5G"
+QJOB_TIME_SLIDENORM="02:00:00"
+
+QJOB_MEM_CP="12G"
+QJOB_TIME_CP="12:00:00"
+
+# Set slideToolKit DIRECTORY
+SLIDETOOLKITDIR="/hpc/local/CentOS7/dhl_ec/software/slideToolKit"
 
 ### START of if-else statement for the number of command-line arguments passed ###
-if [[ $# -lt 0 ]]; then 
+if [[ $# -lt 3 ]]; then 
 	echo "Oh, computer says no! Number of arguments found \"$#\"."
-	script_arguments_error "You must supply correct (number of) arguments when running *** slideQuantify_tiling ***!"
+	script_arguments_error "You must supply correct (number of) arguments when running *** slideJobChecker ***!"
 		
 else
+	
+	echo ""
+	echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
+	echo "Checking consistency of slideToolKit run."
+	
+	### Creating necessary readme
+	echo "* Making necessary 'readme' files..."
+	echo "Slide_num Filename N_Images_Analyzed Message" > ${PROJECTDIR}/readme.${STEP}.${STAIN}.${UNIQUE_LABEL}
 
-	# checking if files exist - if so, skip this script
+	### Setting the patterns to look for -- never change this
+	ERROR_PATTERN="slurmstepd: error:"
+	IMAGESANALYZED_PATTERN="module Images" # only in cellprofiler error file
+	
+	echo "Checking errors-files and zapping them if empty..."
+	for ERRORFILE in $(ls $PROJECTDIR/errors/${STEP}.*.errors); do 
+	
+		if [[ ! -z $(grep "${ERROR_PATTERN}" "${ERRORFILE}") ]] ; then 
 
-	if [[ -d *.tiles ]]
-	then 
-		echo "..... Tiles directory already exists - moving on."
-		exit
-	fi
+			ERRORFILENAME=$(basename $ERRORFILE )
+			SLIDE_NUM=$(basename "$ERRORFILE") | cut -d'.' -f2
+			ERROR_MESSAGE=$(grep "${ERROR_PATTERN}" "${ERRORFILE}")
+			
+# 			N_IMAGES_ANALYZED=$(grep "${IMAGESANALYZED_PATTERN}" "${ERRORFILE}" | wc -l)
+						
+			echoerrorflash "*** ERROR ***  The error-file [ $ERRORFILENAME ] contains an error. We'll keep it there for review and check the contents."
+# 			echoerror "> number of images analyzed................: ${N_IMAGES_ANALYZED}"
+# 			echoerror "> error message............................: ${ERROR_MESSAGE}"
+			echoerror ""
+			echo "${SLIDE_NUM} ${ERRORFILENAME} ${ERROR_MESSAGE} " >> ${PROJECTDIR}/readme.${STEP}.${STAIN}.${UNIQUE_LABEL}
+			
+		else
+	    	
+	    	ERRORFILENAME=$(basename $ERRORFILE )
+			SLIDE_NUM=$(basename "$ERRORFILE") | cut -d'.' -f2
 
-	# loading required modules 
-	module load anaconda/3-8.2021.05
-	module load slideToolKit
-	module load ndpitools
+			N_IMAGES_ANALYZED=$(grep "${IMAGESANALYZED_PATTERN}" "${ERRORFILE}" | wc -l)
+			
+			SUCCESSMESSAGE=$(echosucces "successfully analyzed")
+			SUCCESSMESSAGEREADME=$(echo "success")
+			
+			echosucces "*** SUCCESS *** Step ${STEP} was succefull for slide ${SLIDE_NUM}..."
+			echosucces "Reported in the [ ${ERRORFILENAME} ]:      "
+			echosucces "####################################################################################"
+			head ${ERRORFILE}
+			tail ${ERRORFILE}
+			echosucces "####################################################################################"
+			
+# 			echosucces "> number of images analyzed..................: ${N_IMAGES_ANALYZED}"
+# 			echosucces "> success message............................: ${SUCCESSMESSAGE}"
+			echosucces ""
+			echo "${SLIDE_NUM} ${ERRORFILENAME} ${SUCCESSMESSAGEREADME} " >> ${PROJECTDIR}/readme.${STEP}.${STAIN}.${UNIQUE_LABEL}
 
-	mkdir -pv magick-tmp
-	export MAGICK_TMPDIR=$(pwd)/magick-tmp
-	export TMPDIR=$(pwd)/magick-tmp
+			BASENAME_ERRORFILE=$(basename ERRORFILENAME .errors)
 
-	if [ -f *.ndpi ]; then
-		echo "The image-file is a NDPI and should first be converted to .tif before tiling."
-		slide2Tiles --layer 0 -f *x40*.tif -m *.emask.png;
-
-	elif [ -f *.tif ]; then
-		echo "The image-file is a (NDPI-converted) .tif."
-		slide2Tiles --layer 0 -f *.tif -m *.emask.png;
-
-	elif [ -f *.TIF ]; then
-		# layer 3 is 20x Roche scanner
-		echo "The image-file is a .TIF."
-		slide2Tiles --layer 3 -f *.TIF -m *.emask.png;
-
-	else
-		echoerrorflash "*** ERROR *** Something is rotten in the City of Gotham; most likely a typo. Double back, please. 
-		[image-extension not recognized, should be 'ndpi', 'tif' or 'TIF' ]"
-		exit 1 
-	fi
-
-	# removing temporary files
-	echo "..... Removing temporary directory."
-	rm -rfv magick-tmp
-
-	echo "..... Tiling successfully finished"
+			echo "Removing files [ ${PROJECTDIR}/[errors/logs]/[.errors/.log] ]..."
+# 			rm -v ${PROJECTDIR}/errors/${ERRORFILENAME}
+# 			rm -v ${PROJECTDIR}/logs/${BASENAME_ERRORFILE}.log
+		
+		### END of if-else statement
+		fi
+	
+	### END of for-loop
+	done
+	
 	
 ### END of if-else statement for the number of command-line arguments passed ###
 fi
 
 script_copyright_message
+
