Squash ...

diff --git a/slideQuantify b/slideQuantify
--- a/slideQuantify
+++ b/slideQuantify
@@ -106,7 +106,7 @@ echo ""
 echoitalic "* Written by  : Sander W. van der Laan; Tim Bezemer; Tim van de Kerkhof"
 echoitalic "* E-mail      : s.w.vanderlaan-2@umcutrecht.nl"
 echoitalic "* Last update : 2019-07-11"
-echoitalic "* Version     : 1.1.5"
+echoitalic "* Version     : 1.1.6"
 echo ""
 echoitalic "* Description : This script will start the quantification for a given stain"
 echoitalic "                in a given project directory."
@@ -140,7 +140,7 @@ SLIDETOOLKITDIR="/hpc/local/CentOS7/dhl_ec/software/slideToolKit"
 
 ### START of if-else statement for the number of command-line arguments passed ###
 if [[ $# -lt 7 ]]; then 
-	echo "Oh, computer says no! Number of arguments found "$#"."
+	echo "Oh, computer says no! Number of arguments found \"$#\"."
 	script_arguments_error "You must supply correct (number of) arguments when running *** slideQuantify ***!"
 		
 else
@@ -151,16 +151,16 @@ else
 	mkdir -pv $PROJECTDIR/errors
 	rm -rfv $FILESTART*/magick-tmp
 
-	ENTROPY_THRESHOLD=210
+	ENTROPY_THRESHOLD=210 # should be argument
 	HOLD_JIDS=()
 	INDEX=0
-	BATCH_SIZE=5000
-	UNIQUE_LABEL="V3"
+	BATCH_SIZE=5000 # should be argument, but how exactly does this work?
+	UNIQUE_LABEL="V3" # should be argument
 
 	### FOR DEBUG
 	### DEBUGLIST="AE999.FIBRIN AE99.T02-18575.A.FIBRIN AE997.T05-12460.FIBRIN"
 	### for SLIDE_NUM in $DEBUGLIST; do
-	for SLIDE_NUM in $FILESTART*; do
+	for SLIDE_NUM in ${FILESTART}*; do
 		sleep 1
 		THIS_SLIDE=${SLIDE_NUM/\//}
 		THIS_SLIDEMASK=${THIS_SLIDE}_slideMask_${UNIQUE_LABEL}
@@ -169,7 +169,7 @@ else
 		THIS_CELLPROFILER=${THIS_SLIDE}_CellProfiler_${UNIQUE_LABEL}
 		THIS_WRAPUP=${THIS_SLIDE}_WrapUp_${UNIQUE_LABEL}
 
-		HOLD_JID_INDEX=`expr $INDEX % $BATCH_SIZE`
+		HOLD_JID_INDEX=`expr ${INDEX} % ${BATCH_SIZE}``
 
 		# process batches in smaller chunks
 		if [ "$INDEX" -lt "$BATCH_SIZE" ]; then
@@ -182,10 +182,10 @@ else
 		cd $SLIDE_NUM
 
 		echo ""
-		echobold "Processing images of file [ $SLIDE_NUM ] for staining [ $STAIN ]."
+		echobold "Processing images of file [ ${SLIDE_NUM} ] for staining [ ${STAIN} ] -- at index [ ${INDEX} ] with total batch size [ ${BATCH_SIZE} ]."
 	
-		if [ -f results.txt ]; then 
-			echoitalic "Checking if this file was processed before ....."
+		if [ -s cp_output/*.csv.gz ]; then 
+			echoitalic "Checking if this file was processed before; cp_output/${STAIN}_Image.csv should be present ....."
 			cd ..; 
 			INDEX=$((INDEX+1)); 
 			echo "..... Analysis was already done!"; 
@@ -197,23 +197,23 @@ else
 		echo ""
 		echoitalic "* slideEMask, which will mask, create a macro, and do NDPISplit when necessary."
 		
-		echo "#if [ -f *mask.png ]; then exit; fi;
+		echo "#if [ -s *mask.png ]; then exit; fi;
 		module load slideToolkit
 		module load ndpitools
 		mkdir -pv magick-tmp
 			export MAGICK_TMPDIR=$(pwd)/magick-tmp
 			export TMPDIR=$(pwd)/magick-tmp
 		if [ -f *.ndpi ]; then
-			echo \"The image-file as a NDPI and will be converted to .tif before masking.\"
+			echo \"The image-file is a NDPI and will be converted to .tif before masking.\"
 			if [ -f *.ndpi ]; then  ndpisplit -x40 -z0 *.ndpi; fi
 			slideMask --layer 0 -f *.tif;
 		
 		elif [ -f *.tif ]; then 
-			echo \"The image-file as a (NDPI-converted) .tif.\"
+			echo \"The image-file was NDPI and converted to .tif.\"
 			slideMask --layer 0 -f *.tif;
 		
 		elif [ -f *.TIF ]; then 
-			echo \"The image-file as a .TIF.\"
+			echo \"The image-file is a .TIF.\"
 			slideMask --layer 7 -f *.TIF;
 		
 		else
@@ -223,7 +223,7 @@ else
 		fi
 		slideEMask -f *macro.png -t $ENTROPY_THRESHOLD
 		rm -rfv magick-tmp
-		" | qsub -cwd -N $THIS_SLIDEMASK -e $PROJECTDIR/errors/ -o $PROJECTDIR/logs/ $HOLD_JID_STRING -l h_vmem=$QJOB_MEM_SLIDEMASK -l h_rt=$QJOB_TIME_SLIDEMASK -m ${MAILSETTING} -M ${EMAIL}
+		" | qsub -cwd -N ${THIS_SLIDEMASK} -e ${PROJECTDIR}/errors/ -o ${PROJECTDIR}/logs/ ${HOLD_JID_STRING} -l h_vmem=${QJOB_MEM_SLIDEMASK} -l h_rt=${QJOB_TIME_SLIDEMASK} -m ${MAILSETTING} -M ${EMAIL}
 		### FOR DEBUG
 		### echo $THIS_SLIDEMASK
 		### echo $HOLD_JID_STRING
@@ -240,15 +240,15 @@ else
 		export TMPDIR=$(pwd)/magick-tmp
 
 		if [ -f *.ndpi ]; then
-			echo \"The image-file as a NDPI and will be converted to .tif before tiling.\"
+			echo \"The image-file is a NDPI and will be converted to .tif before tiling.\"
 			slide2Tiles --layer 0 -f *x40*.tif -m *emask.png;
 		
 		elif [ -f *.tif ]; then
-			echo \"The image-file as a (NDPI-converted) .tif.\"
+			echo \"The image-file was NDPI and converted to .tif.\"
 			slide2Tiles --layer 0 -f *.tif -m *.emask.png;
 		
 		elif [ -f *.TIF ]; then
-			echo \"The image-file as a .TIF.\"
+			echo \"The image-file is a .TIF.\"
 			slide2Tiles --layer 7 -f *.TIF -m *.emask.png;
 		
 		else
@@ -257,15 +257,15 @@ else
 			exit 1 
 		fi
 		rm -rfv magick-tmp
-		" | qsub -cwd -N $THIS_SLIDE2TILES -e $PROJECTDIR/errors/ -o $PROJECTDIR/logs/ -hold_jid $THIS_SLIDEMASK -l h_vmem=$QJOB_MEM_SLIDE2TILES -l h_rt=$QJOB_TIME_SLIDE2TILES -m ${MAILSETTING} -M ${EMAIL}
+		" | qsub -cwd -N ${THIS_SLIDE2TILES} -e ${PROJECTDIR}/errors/ -o ${PROJECTDIR}/logs/ -hold_jid ${THIS_SLIDEMASK} -l h_vmem=${QJOB_MEM_SLIDE2TILES} -l h_rt=${QJOB_TIME_SLIDE2TILES} -m ${MAILSETTING} -M ${EMAIL}
 
 		### slideNormalize
 		echo ""
 		echoitalic "* slideNormalize for normalization of images."
 		
-		echo "if [ -f files2cp.txt ]; then exit; fi;
+		echo "if [ -s files2cp.txt ]; then exit; fi;
 		if [ ! -d *.tiles ]; then
-			(>&2 echo "Error! No tiles to process")
+			(>&2 echo "*** ERROR *** No tiles to process. ")
 			exit; 
 		fi
 		cd *.tiles/;
@@ -284,7 +284,7 @@ else
 		cd ..
 		ls -d -1 \$PWD/*tiles/*normalized* > files2cp.txt;
 		ls -d -1 \$PWD/*tiles/ENTROPY* >> files2cp.txt;
-		" | qsub -cwd -N $THIS_SLIDENORMALIZE -e $PROJECTDIR/errors/ -o $PROJECTDIR/logs/ -hold_jid $THIS_SLIDE2TILES -l h_vmem=$QJOB_MEM_SLIDENORM -l h_rt=$QJOB_TIME_SLIDENORM -m ${MAILSETTING} -M ${EMAIL}
+		" | qsub -cwd -N ${THIS_SLIDENORMALIZE} -e ${PROJECTDIR}/errors/ -o ${PROJECTDIR}/logs/ -hold_jid ${THIS_SLIDE2TILES} -l h_vmem=${QJOB_MEM_SLIDENORM} -l h_rt=${QJOB_TIME_SLIDENORM} -m ${MAILSETTING} -M ${EMAIL}
 	
 		### CellProfiler
 		echo ""
@@ -294,7 +294,7 @@ else
 		module load anaconda
 		mkdir -pv cp_output
 		cellprofiler -c -r -p $PIPELINE --file-list files2cp.txt -o cp_output/;
-		" | qsub -cwd -N $THIS_CELLPROFILER -e $PROJECTDIR/errors/ -o $PROJECTDIR/logs/ -hold_jid $THIS_SLIDENORMALIZE -l h_vmem=$QJOB_MEM_CP -l h_rt=$QJOB_TIME_CP -m ${MAILSETTING} -M ${EMAIL}
+		" | qsub -cwd -N ${THIS_CELLPROFILER} -e ${PROJECTDIR}/errors/ -o ${PROJECTDIR}/logs/ -hold_jid ${THIS_SLIDENORMALIZE} -l h_vmem=${QJOB_MEM_CP} -l h_rt=${QJOB_TIME_CP} -m ${MAILSETTING} -M ${EMAIL}
 
 		### REMOVE THIS BREAK FOR PRODUCTION!
 		### When this break is active, only the first item 
@@ -330,7 +330,7 @@ else
 			echo \"Gzipping result files.\";
 			gzip -vf cp_output/${STAIN}*.gct;
 			gzip -vf cp_output/${STAIN}*.csv;
-		" | qsub -cwd -N $THIS_WRAPUP -e $PROJECTDIR/errors/ -o $PROJECTDIR/logs/ -hold_jid $THIS_CELLPROFILER -m ${MAILSETTING} -M ${EMAIL}
+		" | qsub -cwd -N ${THIS_WRAPUP} -e ${PROJECTDIR}/errors/ -o ${PROJECTDIR}/logs/ -hold_jid ${THIS_CELLPROFILER} -m ${MAILSETTING} -M ${EMAIL}
 
 		cd ..
 
