Cleanup help messages

diff --git a/slide2Tiles b/slide2Tiles
--- a/slide2Tiles
+++ b/slide2Tiles
@@ -50,17 +50,16 @@ trap cleanup EXIT
 
 # Errors go to stderr
 err() {
-  echo "ERROR: $@" >&2
+  echo "${SCRIPTNAME} ERROR: $@" >&2
 }
 
 # usage message
 usage() {
 cat <<- EOF
-usage:  
-$SCRIPTNAME [options] -f <filename>
-Try $SCRIPTNAME --help for more information.
+$SCRIPTNAME --help for more information.
 EOF
 }
+
 # help message
 helpMessage() {
 cat <<- EOF
@@ -82,7 +81,6 @@ options:
   [--verbose]               verbose output (for debugging)
   
   --help                    display this help
-  -h                        display usage
 
 examples:
   $SCRIPTNAME --layer 0 "file.tif"
@@ -263,8 +261,7 @@ verbose_debug() {
 checkRequirements() {
   if ! [[ -f "$FILE" ]] ; then
     err "No such file: $FILE"
-    echo
-    helpMessage
+    usage
     exit 1
   fi
   if ! [[ "$MASK" == "" ]] ; then
diff --git a/slideConvert b/slideConvert
--- a/slideConvert
+++ b/slideConvert
@@ -36,15 +36,13 @@ DEPENDENCIES=( $( for el in "${DEPENDENCIES[@]}"; do echo "$el"; done | sort) )
 
 # Errors go to stderr
 err() {
-  echo "ERROR: $@" >&2
+  echo "${SCRIPTNAME} ERROR: $@" >&2
 }
 
 # usage message
 usage() {
 cat <<- EOF
-usage:  
-$SCRIPTNAME -f <filename> 
-Try $SCRIPTNAME --help for more information.
+$SCRIPTNAME --help for more information.
 EOF
 }
 
@@ -62,7 +60,6 @@ options:
   [--bfconvert-args] <arguments>  bfconvert arguments ["$DEFAULT_BFCONVERTARGS"]
 
   --help                    display this help
-  -h                        display usage
 
 examples:
   $SCRIPTNAME "file.ext"
@@ -143,8 +140,7 @@ fi
 checkRequirements() {
   if ! [[ -f "$FILE" ]] ; then
     err "No such file: $FILE"
-    echo
-    helpMessage
+    usage
     exit 1
   fi
 }
diff --git a/slideDirectory b/slideDirectory
--- a/slideDirectory
+++ b/slideDirectory
@@ -32,15 +32,13 @@ DEPENDENCIES=("parallel")
 
 # Errors go to stderr
 err() {
-  echo "ERROR: $@" >&2
+  echo "${SCRIPTNAME} ERROR: $@" >&2
 }
 
 # usage message
 usage() {
 cat <<- EOF
-usage:  
-$SCRIPTNAME -f <filename> 
-Try $SCRIPTNAME --help for more information.
+$SCRIPTNAME --help for more information.
 EOF
 }
 
@@ -56,7 +54,6 @@ options:
   -f, --file <filename>     Move file into a similar named directory 
 
   --help                    display this help
-  -h                        display usage
 
 examples:
   $SCRIPTNAME "file.tif"
@@ -123,8 +120,7 @@ fi
 checkRequirements() {
   if ! [[ -f "$FILE" ]] ; then
     err "No such file: $FILE"
-    echo
-    helpMessage
+    usage
     exit 1
   fi
 }
diff --git a/slideInfo b/slideInfo
--- a/slideInfo
+++ b/slideInfo
@@ -34,15 +34,13 @@ DEPENDENCIES=( $( for el in "${DEPENDENCIES[@]}"; do echo "$el"; done | sort) )
 
 # Errors go to stderr
 err() {
-  echo "ERROR: $@" >&2
+  echo "${SCRIPTNAME} ERROR: $@" >&2
 }
 
 # usage message
 usage() {
 cat <<- EOF
-usage:  
-$SCRIPTNAME -f <filename>
-Try $SCRIPTNAME --help for more information.
+$SCRIPTNAME --help for more information.
 EOF
 }
 
@@ -58,7 +56,6 @@ options:
   -f, --file <filename>       Fetch slide metadata
 
   --help                      display this help
-  -h                          display usage
 
 examples:
   $SCRIPTNAME "file.tif"
@@ -126,8 +123,7 @@ fi
 checkRequirements() {
   if ! [[ -f "$FILE" ]] ; then
     err "No such file: $FILE"
-    echo
-    helpMessage
+    usage
     exit 1
   fi
 }
diff --git a/slideJobsCellProfiler b/slideJobsCellProfiler
--- a/slideJobsCellProfiler
+++ b/slideJobsCellProfiler
@@ -46,7 +46,7 @@ trap cleanup EXIT
 
 # Errors go to stderr
 err() {
-  echo "ERROR: $@" >&2
+  echo "${SCRIPTNAME} ERROR: $@" >&2
 }
 
 # Debug go to stdout
@@ -57,11 +57,10 @@ debug() {
 # usage message
 usage() {
 cat <<- EOF
-usage:  
-$SCRIPTNAME -i <dirname> -p <pipeline> [options]
-Try $SCRIPTNAME --help for more information.
+$SCRIPTNAME --help for more information.
 EOF
 }
+
 # help message
 helpMessage() {
 cat <<- EOF
@@ -83,7 +82,6 @@ qsub:
   [--qsub-args] <arguments>    qsub arguments ("$DEFAULT_QSUBARGS")
 
   --help                       display this help
-  -h                           display usage
 
 examples:
   $SCRIPTNAME -i "./" -p "pipeline.cp"
@@ -211,19 +209,19 @@ checkRequirements() {
   # input dir must exist
   if ! [[ -d "$INPUTDIR" ]] ; then
     err "No such inputdir: $INPUTDIR"
-    helpMessage
+    usage
     exit 1
   fi
   # pipeline must exist
   if ! [[ -f "$PIPELINE" ]] ; then
     err "No such pipeline: $PIPELINE"
-    helpMessage
+    usage
     exit 1
   fi
   # set HANDLER (parallel|qsub|etc)
   if ! [[ "$HANDLER" =~ (qsub|QSUB) || "$HANDLER" == "" ]] ; then
     err "No such job handler: $HANDLER"
-    helpMessage
+    usage
     exit 1
   fi
 }
diff --git a/slideMask b/slideMask
--- a/slideMask
+++ b/slideMask
@@ -38,16 +38,16 @@ DEFAULT_MASKARGS="-blur 40x40 -fuzz 4%"
 
 # Errors go to stderr
 err() {
-  echo "ERROR: $@" >&2
+  echo "${SCRIPTNAME} ERROR: $@" >&2
 }
+
 # usage message
 usage() {
 cat <<- EOF
-usage:  
-$SCRIPTNAME [options] -f <filename>
-Try $SCRIPTNAME --help for more information.
+$SCRIPTNAME --help for more information.
 EOF
 }
+
 # help message
 helpMessage() {
 cat <<- EOF
@@ -65,7 +65,6 @@ options:
   [--mask-args] <arguments>     mask arguments (imageMagick) ["$DEFAULT_MASKARGS"]
   
   --help                        display this help
-  -h                            display usage
 
 examples:
   $SCRIPTNAME "file.tif"
@@ -199,8 +198,7 @@ fi
 checkRequirements() {
   if ! [[ -f "$FILE" ]] ; then
     err "No such file: $FILE"
-    echo
-    helpMessage
+    usage
     exit 1
   fi
 }
diff --git a/slideSQLheader b/slideSQLheader
--- a/slideSQLheader
+++ b/slideSQLheader
@@ -31,19 +31,16 @@ DESCRIPTIONSHORT="Extract SQL-file column names created by cellprofiler"
 DEPENDENCIES=("perl")
 SUFFIX=".head"
 
-#usage message
+# usage message
 usage() {
 cat <<- EOF
-usage:  
-$SCRIPTNAME [options] -f <filename>
-Try $SCRIPTNAME --help for more information.
+$SCRIPTNAME --help for more information.
 EOF
 }
 
-#Errors go to stderr
+# Errors go to stderr
 err() {
-  echo "ERROR: $@" >&2
-  usage
+  echo "${SCRIPTNAME} ERROR: $@" >&2
 }
 
 #help message
@@ -60,7 +57,6 @@ options:
   [--add-head] <filename>   "file.csv" file 
 
   --help                    display this help
-  -h                        display usage
 
 examples:
   $SCRIPTNAME "SQL_SETUP.SQL"
@@ -133,11 +129,13 @@ fi
 checkRequirements() {
   if ! [[ -f "$FILE" ]] ; then
     err "No such file: $FILE">&2;
+    usage
     exit 1
   fi
   if ! [[ -z "$ADDHEAD" ]]; then
     if ! [[ -f "$ADDHEAD" ]] ; then
       err "No such file: $ADDHEAD">&2;
+      usage
       exit 1
     fi  
   fi
diff --git a/slideThumb b/slideThumb
--- a/slideThumb
+++ b/slideThumb
@@ -40,14 +40,13 @@ SUPPORTED_FORMATS=( $( for el in "${SUPPORTED_FORMATS[@]}"; do echo "$el"; done 
 
 # Errors go to stderr
 err() {
-  echo "ERROR: $@" >&2
+  echo "${SCRIPTNAME} ERROR: $@" >&2
 }
+
 # usage message
 usage() {
 cat <<- EOF
-usage:  
-$SCRIPTNAME [options] -f <filename>
-Try $SCRIPTNAME --help for more information.
+$SCRIPTNAME --help for more information.
 EOF
 }
 
@@ -69,7 +68,6 @@ options:
   [--resize] <widthxheight>   maximum output dimentions ["$DEFAULT_RESIZE"]
   
   --help                      display this help
-  -h                          display usage
 
 examples:
   $SCRIPTNAME "file.svs"
@@ -211,8 +209,7 @@ fi
 checkRequirements() {
   if ! [[ -f "$FILE" ]] ; then
     err "No such file: $FILE"
-    echo
-    helpMessage
+    usage
     exit 1
   fi
 }
