re-organize utilities, archived old scripts,  updates to slideJobChecker and slideAppend to work with ExpressHist

diff --git a/slideJobChecker b/slideJobChecker
--- a/slideJobChecker
+++ b/slideJobChecker
@@ -108,14 +108,33 @@ script_arguments_error() {
   	exit 1
 }
 
+script_arguments_error_step_type() {
+			echo "$1"
+			echo ""
+			echo "      *** ERROR *** ERROR --- $(basename "${0}") --- ERROR *** ERROR ***"
+			echo ""
+			echo " You must supply the correct argument:"
+			echo " * [slidemask]         -- Check masking step. [OBSOLETE NOW, as we use ExpressHist]"
+			echo " * [slide2tiles]       -- Check tiling step. Note: ExpressHist-based, a.k.a. we expect error-files conform crossed-tile-masking."
+			echo " * [slidenormalize]    -- Check image normalization step."
+			echo " * [slidecellprofiler] -- Check CellProfiler analysis."
+			echo " * [slidewrapup]       -- Check wrapup of analyses."
+			echo ""
+			echo " Please refer to instruction above."
+			echo ""
+			echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
+			# The wrong arguments are passed, so we'll exit the script now!
+  			exit 1
+}
+
 echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 echobold "                               slideJobChecker"
 echo ""
 echoitalic "* Written by  : Sander W. van der Laan; Tim Bezemer; Tim van de Kerkhof"
 echoitalic "                Yipei Song"
 echoitalic "* E-mail      : s.w.vanderlaan-2@umcutrecht.nl"
-echoitalic "* Last update : 2021-11-18"
-echoitalic "* Version     : 1.0.1"
+echoitalic "* Last update : 2023-02-16"
+echoitalic "* Version     : 1.0.2"
 echo ""
 echoitalic "* Description : This script will check the contents of error files for a "
 echoitalic "                given project directory. "
@@ -161,37 +180,95 @@ else
 	echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 	echo "Checking consistency of slideToolKit run."
 	
-	### Creating necessary readme
-	echo "* Making necessary 'readme' files..."
-	echo "Slide_num Filename N_Images_Analyzed Message" > ${PROJECTDIR}/readme.${STEP}.${STAIN}.${UNIQUE_LABEL}
-
 	### Setting the patterns to look for -- never change this
 	ERROR_PATTERN="slurmstepd: error:"
-	IMAGESANALYZED_PATTERN="module Images" # only in cellprofiler error file
 	
-	echo "Checking errors-files and zapping them if empty..."
+	### Check step-type; should be [slidemask, slide2tiles, slidenormalize, slidecellprofiler, slidewrapup]
+	if [[ ${STEP} = "slidemask" ]]; then
+		echo "Checking masking..."
+		IMAGESANALYZED_PATTERN="module Images" # only in cellprofiler error file
+		### Creating necessary readme
+		echo "* Making necessary 'readme' files..."
+		echo "Slide_num Filename N_Images_Tiled Message" > ${PROJECTDIR}/readme.${STEP}.${STAIN}.${UNIQUE_LABEL}
+	
+	elif [[ ${STEP} = "slide2tiles" ]]; then 
+		echo "Checking tiling results..."
+		
+		IMAGESTILED_PATTERN=": Selected" # only in slide2tiles error file
+		### Creating necessary readme
+		echo "* Making necessary 'readme' files..."
+		echo "Slide_num Filename N_Images_Tiled Message" > ${PROJECTDIR}/readme.${STEP}.${STAIN}.${UNIQUE_LABEL}
+			
+	elif [[ ${STEP} = "slidenormalize" ]]; then
+		echo "Checking image normalization..."
+		IMAGESANALYZED_PATTERN="module Images" # only in cellprofiler error file	
+		### Creating necessary readme
+		echo "* Making necessary 'readme' files..."
+		echo "Slide_num Filename N_Images_Analyzed Message" > ${PROJECTDIR}/readme.${STEP}.${STAIN}.${UNIQUE_LABEL}
+		
+	elif [[ ${STEP} = "slidecellprofiler" ]]; then
+		echo "Checking image analyses..."
+		IMAGESANALYZED_PATTERN="module Images" # only in cellprofiler error file
+		### Creating necessary readme
+		echo "* Making necessary 'readme' files..."
+		echo "Slide_num Filename N_Images_Tiled Message" > ${PROJECTDIR}/readme.${STEP}.${STAIN}.${UNIQUE_LABEL}
+
+	elif [[ ${STEP} = "slidewrapup" ]]; then
+		echo "Checking wrapping of results..."
+		IMAGESANALYZED_PATTERN="module Images" # only in cellprofiler error file
+		### Creating necessary readme
+		echo "* Making necessary 'readme' files..."
+		echo "Slide_num Filename N_Images_Tiled Message" > ${PROJECTDIR}/readme.${STEP}.${STAIN}.${UNIQUE_LABEL}
+
+	else 
+		script_arguments_error_step_type "You must supply correct step-type when running *** slideJobChecker ***!"
+	
+	### END of if-else statement
+	fi
+	
+	### start checking	
+	echo "Checking errors-files and g-zapping them if successfull..."
 	for ERRORFILE in $(ls $PROJECTDIR/errors/${STEP}.*.errors); do 
 	
 		if [[ ! -z $(grep "${ERROR_PATTERN}" "${ERRORFILE}") ]] ; then 
 
 			ERRORFILENAME=$(basename $ERRORFILE )
-			SLIDE_NUM=$(basename "$ERRORFILE") | cut -d'.' -f2
+			SLIDE_NUM=$(basename "${ERRORFILENAME}" | cut -d'.' -f2)
+			
 			ERROR_MESSAGE=$(grep "${ERROR_PATTERN}" "${ERRORFILE}")
 			
-			N_IMAGES_ANALYZED=$(grep "${IMAGESANALYZED_PATTERN}" "${ERRORFILE}" | wc -l)
+			N_IMAGES=$(grep "${IMAGESANALYZED_PATTERN}" "${ERRORFILE}" | wc -l)
 						
 			echoerrorflash "*** ERROR ***  The error-file [ $ERRORFILENAME ] contains an error. We'll keep it there for review and check the contents."
-			echoerror "> number of images analyzed................: ${N_IMAGES_ANALYZED}"
+			echoerror "> number of images analyzed/tiled..........: ${N_IMAGES}"
 # 			echoerror "> error message............................: ${ERROR_MESSAGE}"
 			echoerror ""
-			echo "${SLIDE_NUM} ${ERRORFILENAME} ${ERROR_MESSAGE} " >> ${PROJECTDIR}/readme.${STEP}.${STAIN}.${UNIQUE_LABEL}
+			echo "${SLIDE_NUM} ${ERRORFILENAME} ${ERROR_MESSAGE} **ERROR**" >> ${PROJECTDIR}/readme.${STEP}.${STAIN}.${UNIQUE_LABEL}
 			
 		else
 			
 			ERRORFILENAME=$(basename $ERRORFILE )
-			SLIDE_NUM=$(basename "$ERRORFILE") | cut -d'.' -f2
+			SLIDE_NUM=$(basename "${ERRORFILENAME}" | cut -d'.' -f2)
 
-			N_IMAGES_ANALYZED=$(grep "${IMAGESANALYZED_PATTERN}" "${ERRORFILE}" | wc -l)
+			if [[ ${STEP} = "slidemask" ]]; then
+				N_IMAGES=$(grep "${IMAGESANALYZED_PATTERN}" "${ERRORFILE}" | wc -l)
+
+			elif [[ ${STEP} = "slide2tiles" ]]; then
+				N_IMAGES=$(grep "${IMAGESTILED_PATTERN}" "${ERRORFILE}" | awk '{ print $5 }')
+			
+			elif [[ ${STEP} = "slidenormalize" ]]; then
+				N_IMAGES=$(grep "${IMAGESANALYZED_PATTERN}" "${ERRORFILE}" | wc -l)
+			
+			elif [[ ${STEP} = "slidecellprofiler" ]]; then
+				N_IMAGES=$(grep "${IMAGESANALYZED_PATTERN}" "${ERRORFILE}" | wc -l)
+				
+			elif [[ ${STEP} = "slidewrapup" ]]; then
+				N_IMAGES=$(grep "${IMAGESANALYZED_PATTERN}" "${ERRORFILE}" | wc -l)
+			else 
+				script_arguments_error_step_type "You must supply correct step-type when running *** slideJobChecker ***!"
+	
+			### END of if-else statement
+			fi
 			
 			SUCCESSMESSAGE=$(echosucces "successfully analyzed")
 			SUCCESSMESSAGEREADME=$(echo "success")
@@ -203,16 +280,16 @@ else
 			tail ${ERRORFILE}
 			echosucces "####################################################################################"
 			
-			echosucces "> number of images analyzed..................: ${N_IMAGES_ANALYZED}"
+			echosucces "> number of images analyzed/tiled............: ${N_IMAGES}"
 # 			echosucces "> success message............................: ${SUCCESSMESSAGE}"
 			echosucces ""
-			echo "${SLIDE_NUM} ${ERRORFILENAME} ${SUCCESSMESSAGEREADME} " >> ${PROJECTDIR}/readme.${STEP}.${STAIN}.${UNIQUE_LABEL}
+			echo "${SLIDE_NUM} ${ERRORFILENAME} ${N_IMAGES} ${SUCCESSMESSAGEREADME} " >> ${PROJECTDIR}/readme.${STEP}.${STAIN}.${UNIQUE_LABEL}
 
-			BASENAME_ERRORFILE=$(basename ERRORFILENAME .errors)
+			BASENAME_ERRORFILE=$(basename /${ERRORFILENAME} .errors)
 
-# 			echo "Removing files [ ${PROJECTDIR}/[errors/logs]/[.errors/.log] ]..."
-# 			rm -v ${PROJECTDIR}/errors/${ERRORFILENAME}
-# 			rm -v ${PROJECTDIR}/logs/${BASENAME_ERRORFILE}.log
+			echo "Gzipping files [ ${PROJECTDIR}/[errors/logs]/[.errors/.log] ]..."
+			gzip -vf ${PROJECTDIR}/errors/${ERRORFILENAME}
+			gzip -vf ${PROJECTDIR}/logs/${BASENAME_ERRORFILE}.log
 		
 		### END of if-else statement
 		fi
