start on edit for macOS local version

diff --git a/slideQuantifyOSX b/slideQuantifyOSX
--- a/slideQuantifyOSX
+++ b/slideQuantifyOSX
@@ -92,24 +92,36 @@ script_arguments_error() {
 	echoerror "- Argument #4  -- starting letters/characters of the image-subdirectories, e.g. IMG or AE or AAA."
 	echoerror "- Argument #5  -- output filename where the CellProfiler results are stored, e.g. Image.txt (delimiter is assumed '_')."
 	echoerror ""
-	echoerror "An example command would be: slideQuantify [arg1: STAIN] [arg2: path_to_cellprofiler_pipeline] [arg3: path_to_working_directory] [arg4: IMG or AE or AAA] [arg5: Image.txt]"
+	echoerror "- Argument #1  -- name of the stain as it appears in the filenames, e.g. FIBRIN."
+	echoerror "- Argument #2  -- path_to CellProfiler pipeline, e.g. FIBRIN.cppipe."
+	echoerror "- Argument #3  -- path_to working directory, i.e. where all the image-subdirectories are."
+	echoerror "- Argument #4  -- starting letters/characters of the image-subdirectories, e.g. IMG or AE or AAA."
+	echoerror "- Argument #5  -- output filename where the CellProfiler results are stored, e.g. Image.csv (delimiter is assumed '_')."
+	echoerror "- Argument #6  -- eMask threshold. A smaller number is less stringent, best results are obtained using, e.g. '210'."
+	echoerror ""
+	echoerror "An example command would be: slideQuantifyOSX [arg1: STAIN] [arg2: path_to_cellprofiler_pipeline] [arg3: path_to_working_directory] [arg4: IMG or AE or AAA] [arg5: Image.txt] [arg6: 210]"
+	echoerror ""
+	echoerror "Please note that this command should be run within the working directory (Argument #3)."
+
 	echoerror "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
   	# The wrong arguments are passed, so we'll exit the script now!
   	exit 1
 }
 
 echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
-echobold "                               slideQuantify"
+echobold "                               slideQuantifyOSX"
 echo ""
 echoitalic "* Written by  : Sander W. van der Laan; Tim Bezemer; Tim van de Kerkhof"
+echoitalic "                Yipei Song"
 echoitalic "* E-mail      : s.w.vanderlaan-2@umcutrecht.nl"
-echoitalic "* Last update : 2019-07-03"
-echoitalic "* Version     : 1.1.3-beta"
+echoitalic "* Last update : 2021-08-31"
+echoitalic "* Version     : 2.0.2"
 echo ""
 echoitalic "* Description : This script will start the quantification for a given stain"
-echoitalic "                in a given project directory."
+echoitalic "                in a given project directory on macOS, for instance"
+echoitalic "                your iMac, mac mini or MacBook"
 echo ""
-echocyan "NOTE: this is the macOS (10.14.5+) version for local use."
+echocyan "NOTE: this *only* works on macOS (10.14.5+)."
 echo ""
 echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 
@@ -120,6 +132,7 @@ PIPELINE="$2" # Depends on arg2
 PROJECTDIR="$3" # Depends on arg3
 FILESTART="$4" # Depends on arg4
 OUTPUTFILENAME="$5" # Depends on arg5
+EMASKTHRESHOLD="$6" # Depends on arg6
 
 ### Set slideToolKit DIRECTORY
 SLIDETOOLKITDIR="~/git/swvanderlaan/slideToolKit"
@@ -133,16 +146,17 @@ else
 	echobold "Cleaning up house, first."
 	rm -rfv $FILESTART*/magick-tmp
 
-	ENTROPY_THRESHOLD=210
-	HOLD_JIDS=()
+	ENTROPY_THRESHOLD="$EMASKTHRESHOLD" 
+# 	HOLD_JIDS=()
 	INDEX=0
-	BATCH_SIZE=5000
-	UNIQUE_LABEL="V3"
+	BATCH_SIZE=5000 # should be argument, but how exactly does this work?
+	UNIQUE_LABEL="V3" # should be argument
 
 	### FOR DEBUG
-	### DEBUGLIST="AE1686.T07-11206.CD3.20141216 AE1927.T08-12829.CD3.20141216 AE337.T06-19497.CD3.20141218 AE1827.T09-14098.CD3 AE2191.UMC.CD3.20141216 AE921.T05-16731.CD3.20150901"
-	### for SLIDE_NUM in $DEBUGLIST; do
-	for SLIDE_NUM in $FILESTART*; do
+	echocyan "Debug mode - processing debug-images."
+	DEBUGLIST="AE1088.UMC.CD3_CD56_NKT AE2292.UMC.CD3_CD56_NKT AE861.UMC.CD3_CD56_NKT AE3892.UMC.CD3_CD56_NKT"
+	for SLIDE_NUM in $DEBUGLIST; do
+# 	for SLIDE_NUM in $FILESTART*; do
 		sleep 1
 		THIS_SLIDE=${SLIDE_NUM/\//}
 		THIS_SLIDEMASK=${THIS_SLIDE}_slideMask_${UNIQUE_LABEL}
@@ -151,137 +165,202 @@ else
 		THIS_CELLPROFILER=${THIS_SLIDE}_CellProfiler_${UNIQUE_LABEL}
 		THIS_WRAPUP=${THIS_SLIDE}_WrapUp_${UNIQUE_LABEL}
 
-		HOLD_JID_INDEX=`expr $INDEX % $BATCH_SIZE`
-
-		# process batches in smaller chunks
-		if [ "$INDEX" -lt "$BATCH_SIZE" ]; then
-			HOLD_JID_STRING=""
-		else
-			HOLD_JID_STRING="-hold_jid ${HOLD_JIDS[$HOLD_JID_INDEX]}"
-		fi
-		HOLD_JIDS[$HOLD_JID_INDEX]=$THIS_CELLPROFILER
+# 		HOLD_JID_INDEX=`expr $INDEX % $BATCH_SIZE`
+# 
+# 		# process batches in smaller chunks
+# 		if [ "$INDEX" -lt "$BATCH_SIZE" ]; then
+# 			HOLD_JID_STRING=""
+# 		else
+# 			HOLD_JID_STRING="-hold_jid ${HOLD_JIDS[$HOLD_JID_INDEX]}"
+# 		fi
+# 		HOLD_JIDS[$HOLD_JID_INDEX]=$THIS_CELLPROFILER
 	
 		cd $PROJECTDIR/$SLIDE_NUM
 
+		echobold "Processing images of file [ ${SLIDE_NUM} ] in directory [ ${PROJECTDIR} ] for staining [ ${STAIN} ] -- at index [ ${INDEX} ] with total batch size [ ${BATCH_SIZE} ]."	
+		cd "$SLIDE_NUM" || exit
 		echo ""
-		echobold "Processing images of file [ $SLIDE_NUM ] for staining [ $STAIN ]."
 	
-		if [ -f results.txt ]; then 
-			echoitalic "Checking if this file was processed before ....."
-			cd ..; 
+		if [[ -s cp_output/"$STAIN"_Image.csv.gz ]]; then 
+			echoitalic "Checking if this file was processed before; cp_output/${STAIN}_Image.csv.gz should be present ....."
+			ls -lh cp_output/*.gz
+			cd .. ; 
 			INDEX=$((INDEX+1)); 
 			echo "..... Analysis was already done!"; 
 			continue; 
 		fi
-		echo "..... Processing file for the first time."
 		
+		echo "..... Processing file for the first time. Submitting job for: "
+		
+		rm -rfv "$PROJECTDIR"/logs/"$SLIDE_NUM"*
+		rm -rfv "$PROJECTDIR"/errors/"$SLIDE_NUM"*
+
 		### slideEMask for macro, and NDPISplit when necessary
 		echo ""
-		echoitalic "* slideEMask, which will mask, create a macro, and do NDPISplit when necessary. [ $THIS_SLIDEMASK ]"
-		
-		### NOTE: this does not work locally on macOS
-		### if [[ -f *mask.png ]]; then 
-		### 	echo "..... Entropy mask already exists."
-		### 	continue; 
-		### fi;
-		mkdir -pv magick-tmp
-			export MAGICK_TMPDIR=$(pwd)/magick-tmp
-			export TMPDIR=$(pwd)/magick-tmp
-		if [ -f *.ndpi ]; then
-			echo "The image-file is a NDPI and will be converted to .tif before masking."
-			if [ -f *.ndpi ]; then  ndpisplit -x40 -z0 *.ndpi; fi
-			slideMask --layer 0 -f *.tif;
-		
-		elif [ -f *.tif ]; then 
-			echo "The image-file is a (NDPI-converted) .tif."
-			slideMask --layer 0 -f *.tif;
-		
-		elif [ -f *.TIF ]; then 
-			echo "The image-file is a .TIF."
-			slideMask --layer 7 -f *.TIF;
-		
-		else
-			echoerrorflash \"*** ERROR *** Something is rotten in the City of Gotham; most likely a typo. Double back, please. 
-			[image-extension not recognized, should be 'ndpi', 'tif' or 'TIF' ]\"	
-			exit 1 
-		fi
-		
-		echo "..... Applying entropy filter over [*.macro.png]."
-		slideEMask -f *macro.png -t $ENTROPY_THRESHOLD
-		echo "..... Removing temporary directory."
-		rm -rfv magick-tmp
+		echoitalic "* slideEMask, which will mask, create a macro, and do NDPISplit when necessary."
 
-		### FOR DEBUG
-		### echo $THIS_SLIDEMASK
-		### echo $HOLD_JID_STRING
-	
-		### slide2Tiles
-		echo ""
-		echoitalic "* slide2Tiles to create tiles from images. [ $THIS_SLIDE2TILES ]"
-		
-		### NOTE: this does not work locally on macOS
-		### if [ -d *.tiles ]; then 
-		### 	echo "..... Tiles directory already exists."
-		### 	continue; 
-		### fi;
+		# checking if masks exist - if so, skip this script
+		if [[ -s *mask.png ]] 
+		then 
+			exit 
+		fi
 
 		mkdir -pv magick-tmp
 		export MAGICK_TMPDIR=$(pwd)/magick-tmp
 		export TMPDIR=$(pwd)/magick-tmp
 
 		if [ -f *.ndpi ]; then
-			echo "The image-file is a NDPI and will be converted to .tif before tiling."
-			slide2Tiles --layer 0 -f *x40*.tif -m *emask.png;
-		
-		elif [ -f *.tif ]; then
-			echo "The image-file is a (NDPI-converted) .tif."
-			slide2Tiles --layer 0 -f *.tif -m *.emask.png;
-		
-		elif [ -f *.TIF ]; then
-			echo "The image-file is a .TIF."
-			slide2Tiles --layer 7 -f *.TIF -m *.emask.png;
-		
+			echo \"The image-file is a NDPI and will be converted to .tif before masking.\"
+			if [ -f *.ndpi ]; then  ndpisplit -x40 -z0 *.ndpi; fi
+			slideMask --layer 0 -f *.tif;
+
+		elif [ -f *.tif ]; then 
+			echo \"The image-file was a NDPI-converted .tif.\"
+			slideMask --layer 0 -f *.tif;
+
+		elif [ -f *.TIF ]; then 
+			echo \"The image-file is a .TIF.\"
+			slideMask --layer 3 -f *.TIF;
+
 		else
 			echoerrorflash \"*** ERROR *** Something is rotten in the City of Gotham; most likely a typo. Double back, please. 
-			[image-extension not recognized, should be 'ndpi', 'tif' or 'TIF' ]\"	
+			[image-extension not recognized, should be 'ndpi', 'tif' or 'TIF' ]\"
 			exit 1 
 		fi
-		echo "..... Removing temporary directory."
-		rm -rfv magick-tmp
 
-		### slideNormalize
-		echo ""
-		echoitalic "* slideNormalize for normalization of images. [ $THIS_SLIDENORMALIZE ]."
-		
-		### NOTE: this does not work locally on macOS
-		### if [ -f files2cp.txt ]; then 
-		### 	echo "Normalization was already applied."
-		### 	continue; 
-		### fi;
-		if [ ! -d *.tiles ]; then
-			(>&2 echo "*** ERROR *** No tiles to process.")
-			exit; 
-		fi
-		
-		### DEBUG
-		### echo "...Checking existence of tiles."
-		### ls $PROJECTDIR/$SLIDE_NUM/*.tiles/;
-		cd $PROJECTDIR/$SLIDE_NUM/*.tiles/;
-
-		mkdir -pv magick-tmp
-			export MAGICK_TMPDIR=$(pwd)/magick-tmp
-			export TMPDIR=$(pwd)/magick-tmp
-		for MASKED_IMAGE_TILE in *.png; do
-			echo "...Processing tile [ $MASKED_IMAGE_TILE ]"
-			echo "... - applying normalization ..."
-			slideNormalize $MASKED_IMAGE_TILE
-			
-			echo "... - masking the normalized image ..."
-			slideEMask -c -f $MASKED_IMAGE_TILE -t $ENTROPY_THRESHOLD
-			rm -v $MASKED_IMAGE_TILE;
+		# running slideMask on the macro
+		for MACRO in $(ls *.macro.*); do 
+			slideEMask -f $MACRO -t $EMASKTHRESHOLD; 
+	
 		done
+
+		# removing temporary files
 		rm -rfv magick-tmp
-		cd ..
+
+
+
+
+
+
+# 		echo ""
+# 		echobold "Processing images of file [ $SLIDE_NUM ] for staining [ $STAIN ]."
+# 	
+# 		if [ -f results.txt ]; then 
+# 			echoitalic "Checking if this file was processed before ....."
+# 			cd ..; 
+# 			INDEX=$((INDEX+1)); 
+# 			echo "..... Analysis was already done!"; 
+# 			continue; 
+# 		fi
+# 		echo "..... Processing file for the first time."
+# 		
+# 		### slideEMask for macro, and NDPISplit when necessary
+# 		echo ""
+# 		echoitalic "* slideEMask, which will mask, create a macro, and do NDPISplit when necessary. [ $THIS_SLIDEMASK ]"
+# 		
+# 		### NOTE: this does not work locally on macOS
+# 		### if [[ -f *mask.png ]]; then 
+# 		### 	echo "..... Entropy mask already exists."
+# 		### 	continue; 
+# 		### fi;
+# 		mkdir -pv magick-tmp
+# 			export MAGICK_TMPDIR=$(pwd)/magick-tmp
+# 			export TMPDIR=$(pwd)/magick-tmp
+# 		if [ -f *.ndpi ]; then
+# 			echo "The image-file is a NDPI and will be converted to .tif before masking."
+# 			if [ -f *.ndpi ]; then  ndpisplit -x40 -z0 *.ndpi; fi
+# 			#slideMask --layer 0 -f *.tif;
+# 		
+# 		elif [ -f *.tif ]; then 
+# 			echo "The image-file is a (NDPI-converted) .tif."
+# 			slideMask --layer 0 -f *.tif;
+# 		
+# 		elif [ -f *.TIF ]; then 
+# 			echo "The image-file is a .TIF."
+# 			slideMask --layer 7 -f *.TIF;
+# 		
+# 		else
+# 			echoerrorflash \"*** ERROR *** Something is rotten in the City of Gotham; most likely a typo. Double back, please. 
+# 			[image-extension not recognized, should be 'ndpi', 'tif' or 'TIF' ]\"	
+# 			exit 1 
+# 		fi
+# 		
+# 		echo "..... Applying entropy filter over [*.macro.png]."
+# 		slideEMask -f *macro.png -t $ENTROPY_THRESHOLD
+# 		echo "..... Removing temporary directory."
+# 		rm -rfv magick-tmp
+
+		### FOR DEBUG
+		### echo $THIS_SLIDEMASK
+		### echo $HOLD_JID_STRING
+	
+# 		### slide2Tiles
+# 		echo ""
+# 		echoitalic "* slide2Tiles to create tiles from images. [ $THIS_SLIDE2TILES ]"
+# 		
+# 		### NOTE: this does not work locally on macOS
+# 		### if [ -d *.tiles ]; then 
+# 		### 	echo "..... Tiles directory already exists."
+# 		### 	continue; 
+# 		### fi;
+# 
+# 		mkdir -pv magick-tmp
+# 		export MAGICK_TMPDIR=$(pwd)/magick-tmp
+# 		export TMPDIR=$(pwd)/magick-tmp
+# 
+# 		if [ -f *.ndpi ]; then
+# 			echo "The image-file is a NDPI and will be converted to .tif before tiling."
+# 			slide2Tiles --layer 0 -f *x40*.tif -m *emask.png;
+# 		
+# 		elif [ -f *.tif ]; then
+# 			echo "The image-file is a (NDPI-converted) .tif."
+# 			slide2Tiles --layer 0 -f *.tif -m *.emask.png;
+# 		
+# 		elif [ -f *.TIF ]; then
+# 			echo "The image-file is a .TIF."
+# 			slide2Tiles --layer 7 -f *.TIF -m *.emask.png;
+# 		
+# 		else
+# 			echoerrorflash \"*** ERROR *** Something is rotten in the City of Gotham; most likely a typo. Double back, please. 
+# 			[image-extension not recognized, should be 'ndpi', 'tif' or 'TIF' ]\"	
+# 			exit 1 
+# 		fi
+# 		echo "..... Removing temporary directory."
+# 		rm -rfv magick-tmp
+# 
+# 		### slideNormalize
+# 		echo ""
+# 		echoitalic "* slideNormalize for normalization of images. [ $THIS_SLIDENORMALIZE ]."
+# 		
+# 		### NOTE: this does not work locally on macOS
+# 		### if [ -f files2cp.txt ]; then 
+# 		### 	echo "Normalization was already applied."
+# 		### 	continue; 
+# 		### fi;
+# 		if [ ! -d *.tiles ]; then
+# 			(>&2 echo "*** ERROR *** No tiles to process.")
+# 			exit; 
+# 		fi
+# 		
+# 		### DEBUG
+# 		### echo "...Checking existence of tiles."
+# 		### ls $PROJECTDIR/$SLIDE_NUM/*.tiles/;
+# 		cd $PROJECTDIR/$SLIDE_NUM/*.tiles/;
+# 
+# 		mkdir -pv magick-tmp
+# 			export MAGICK_TMPDIR=$(pwd)/magick-tmp
+# 			export TMPDIR=$(pwd)/magick-tmp
+# 		for MASKED_IMAGE_TILE in *.png; do
+# 			echo "...Processing tile [ $MASKED_IMAGE_TILE ]"
+# 			echo "... - applying normalization ..."
+# 			slideNormalize $MASKED_IMAGE_TILE
+# 			
+# 			echo "... - masking the normalized image ..."
+# 			slideEMask -c -f $MASKED_IMAGE_TILE -t $ENTROPY_THRESHOLD
+# 			rm -v $MASKED_IMAGE_TILE;
+# 		done
+# 		rm -rfv magick-tmp
+# 		cd ..
 # 		echo "...Collecting all normalized and masked tiles in a file for CellProfiler."
 # 		ls -d -1 $(pwd)/*tiles/*normalized* > files2cp.txt
 # 		ls -d -1 $(pwd)/*tiles/ENTROPY* >> files2cp.txt
@@ -303,11 +382,22 @@ else
 # 			
 # 		fi
 # 
-# 		### REMOVE THIS BREAK FOR PRODUCTION!
-# 		### When this break is active, only the first item 
-# 		### in the list of items to be processed will be processed.
-# 		INDEX=$((INDEX+1))
-# # 		break;	
+		### REMOVE THIS BREAK FOR PRODUCTION!
+		### When this break is active, only the first item 
+		### in the list of items to be processed will be processed.
+		###
+		### OLD CODE
+		### INDEX=$((INDEX+1))
+		### break;	
+		
+		### NEW CODE
+		cd ..
+		
+		INDEX=$((INDEX+1))
+		if [ "$INDEX" -eq "$BATCH_SIZE" ]; then 
+			break; 
+		fi
+		
 # 
 # 		### Wrap Up
 # 		echo ""
@@ -334,16 +424,12 @@ else
 # 		fi;
 # 			echo "Removing list of files to process.";
 # 			#rm -v files2cp.txt;
-# 
-		cd ..
 
-		INDEX=$((INDEX+1))
-		if [ "$INDEX" -eq "$BATCH_SIZE" ]; then 
-			break;
-		fi
-		
+
+	# END OF for-loop
 	done
-	
+
+
 ### END of if-else statement for the number of command-line arguments passed ###
 fi
 
