Additions, updates, edits, corrections to slideQuantify and underlying scripts. Also added CD3-CD56-NKT pipeline. Changed the name of the SGE-based slideQuantify script. Everything is now SLURM-based. Added arguments and variables to the underlying scripts.

diff --git a/slideQuantifySGE b/slideQuantifySGE
--- a/slideQuantifySGE
+++ b/slideQuantifySGE
@@ -90,14 +90,12 @@ script_arguments_error() {
 	echoerror "- Argument #2  -- path_to CellProfiler pipeline, e.g. FIBRIN.cppipe."
 	echoerror "- Argument #3  -- path_to working directory, i.e. where all the image-subdirectories are."
 	echoerror "- Argument #4  -- starting letters/characters of the image-subdirectories, e.g. IMG or AE or AAA."
-	echoerror "- Argument #5  -- output filename where the CellProfiler results are stored, e.g. Image.csv (delimiter is assumed '_')."
+	echoerror "- Argument #5  -- output filename where the CellProfiler results are stored, e.g. Image.txt (delimiter is assumed '_')."
 	echoerror "- Argument #6  -- email address to send aborted/error jobs too, e.g. y.name@umcutrecht.nl."
-	echoerror "- Argument #7  -- by default emails are send when jobs are aborted/error, you can change that here, e.g. you can choose: BEGIN=begin of job; END=end of job; FAIL=abort of job; ALL=all message job; NONE=no mail is send."
+	echoerror "- Argument #7  -- by default emails are send when jobs are aborted/error, you can change that here, e.g. you can choose: b=begin of job; e=end of job; a=abort of job; s=suspended job; n=no mail is send."
 	echoerror "- Argument #8  -- eMask threshold. A smaller number is less stringent, best results are obtained using, e.g. '210'."
 	echoerror ""
 	echoerror "An example command would be: slideQuantify [arg1: STAIN] [arg2: path_to_cellprofiler_pipeline] [arg3: path_to_working_directory] [arg4: IMG or AE or AAA] [arg5: Image.txt] [arg6: y.name@umcutrecht.nl] [arg7: a] [arg8: 210]"
-	echoerror ""
-	echoerror "Please note that this command should be run within the working directory (Argument #3)."
 	echoerror "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
   	# The wrong arguments are passed, so we'll exit the script now!
   	exit 1
@@ -107,14 +105,12 @@ echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 echobold "                               slideQuantify"
 echo ""
 echoitalic "* Written by  : Sander W. van der Laan; Tim Bezemer; Tim van de Kerkhof"
-echoitalic "                Yipei Song"
 echoitalic "* E-mail      : s.w.vanderlaan-2@umcutrecht.nl"
-echoitalic "* Last update : 2021-08-24"
-echoitalic "* Version     : 2.0"
+echoitalic "* Last update : 2019-07-23"
+echoitalic "* Version     : 1.1.8"
 echo ""
 echoitalic "* Description : This script will start the quantification for a given stain"
-echoitalic "                in a given project directory. "
-echoitalic "                This is SLURM based."
+echoitalic "                in a given project directory."
 echo ""
 echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 
@@ -144,8 +140,6 @@ QJOB_TIME_CP="09:00:00"
 # Set slideToolKit DIRECTORY
 SLIDETOOLKITDIR="/hpc/local/CentOS7/dhl_ec/software/slideToolKit"
 
-TESTDIR="/hpc/dhl_ec/VirtualSlides/Projects/AE_20180305_SJAGER_HSSCHIPPER_FVERVERS_SBIJKERK/CD3_CD56_NKT"
-
 ### START of if-else statement for the number of command-line arguments passed ###
 if [[ $# -lt 8 ]]; then 
 	echo "Oh, computer says no! Number of arguments found \"$#\"."
@@ -164,9 +158,9 @@ else
 	UNIQUE_LABEL="V3" # should be argument
 
 	### FOR DEBUG
-	DEBUGLIST="AE999.FIBRIN AE99.T02-18575.A.FIBRIN AE997.T05-12460.FIBRIN"
-	for SLIDE_NUM in "$DEBUGLIST"*; do
-# 	for SLIDE_NUM in "$FILESTART"*; do
+	### DEBUGLIST="AE999.FIBRIN AE99.T02-18575.A.FIBRIN AE997.T05-12460.FIBRIN"
+	### for SLIDE_NUM in $DEBUGLIST; do
+	for SLIDE_NUM in "$FILESTART"*; do
 		sleep 1
 		THIS_SLIDE=${SLIDE_NUM/\//}
 		THIS_SLIDEMASK=${THIS_SLIDE}_slideMask_${UNIQUE_LABEL}
@@ -184,10 +178,10 @@ else
 			HOLD_JID_STRING="-hold_jid ${HOLD_JIDS[$HOLD_JID_INDEX]}"
 		fi
 		HOLD_JIDS[$HOLD_JID_INDEX]=$THIS_CELLPROFILER
-
-		echobold "Processing images of file [ ${SLIDE_NUM} ] in directory [ ${PROJECTDIR} ] for staining [ ${STAIN} ] -- at index [ ${INDEX} ] with total batch size [ ${BATCH_SIZE} ]."	
+	
 		cd "$SLIDE_NUM" || exit
 		echo ""
+		echobold "Processing images of file [ ${SLIDE_NUM} ] for staining [ ${STAIN} ] -- at index [ ${INDEX} ] with total batch size [ ${BATCH_SIZE} ]."
 	
 		if [[ -s cp_output/"$STAIN"_Image.csv.gz ]]; then 
 			echoitalic "Checking if this file was processed before; cp_output/${STAIN}_Image.csv.gz should be present ....."
@@ -207,8 +201,33 @@ else
 	echo ""
 	echoitalic "* slideEMask, which will mask, create a macro, and do NDPISplit when necessary."
 	
-	JOB_ID_THIS_SLIDEMASK=$(sbatch -J ${THIS_SLIDEMASK} -e ${PROJECTDIR}/errors/slidemask.errors -o ${PROJECTDIR}/logs/slidemask.log ${HOLD_JID_STRING} --mem=${QJOB_MEM_SLIDEMASK} --time=${QJOB_TIME_SLIDEMASK} --mail-type=${MAILSETTING} --mail-user=${EMAIL} --parsable ${TESTDIR}/slideQuantify_mask.sh)
+	echo "#if [ -s *mask.png ]; then exit; fi;
+	module load slideToolkit
+	module load ndpitools
+	mkdir -pv magick-tmp
+		export MAGICK_TMPDIR=$(pwd)/magick-tmp
+		export TMPDIR=$(pwd)/magick-tmp
+	if [ -f *.ndpi ]; then
+		echo \"The image-file is a NDPI and will be converted to .tif before masking.\"
+		if [ -f *.ndpi ]; then  ndpisplit -x40 -z0 *.ndpi; fi
+		slideMask --layer 0 -f *.tif;
 	
+	elif [ -f *.tif ]; then 
+		echo \"The image-file was NDPI and converted to .tif.\"
+		slideMask --layer 0 -f *.tif;
+	
+	elif [ -f *.TIF ]; then 
+		echo \"The image-file is a .TIF.\"
+		slideMask --layer 3 -f *.TIF;
+	
+	else
+		echoerrorflash \"*** ERROR *** Something is rotten in the City of Gotham; most likely a typo. Double back, please. 
+		[image-extension not recognized, should be 'ndpi', 'tif' or 'TIF' ]\"	
+		exit 1 
+	fi
+	slideEMask -f *macro.png -t $ENTROPY_THRESHOLD
+	rm -rfv magick-tmp
+	" | qsub -cwd -N ${THIS_SLIDEMASK} -e ${PROJECTDIR}/errors/ -o ${PROJECTDIR}/logs/ ${HOLD_JID_STRING} -l h_vmem=${QJOB_MEM_SLIDEMASK} -l h_rt=${QJOB_TIME_SLIDEMASK} -m ${MAILSETTING} -M ${EMAIL}
 	### FOR DEBUG
 	### echo $THIS_SLIDEMASK
 	### echo $HOLD_JID_STRING
@@ -217,24 +236,70 @@ else
 	echo ""
 	echoitalic "* slide2Tiles to create tiles from images."
 	
-	JOB_ID_THIS_SLIDE2TILES=$(sbatch -J ${THIS_SLIDE2TILES} -e ${PROJECTDIR}/errors/slide2tiles.errors -o ${PROJECTDIR}/logs/slide2tiles.log --mem=${QJOB_MEM_SLIDE2TILES} --time=${QJOB_TIME_SLIDE2TILES} --mail-type=${MAILSETTING} --mail-user=${EMAIL} --depend=afterany:$JOB_ID_THIS_SLIDEMASK --parsable ${TESTDIR}/slideQuantify_tiling.sh)
-	
+	echo "if [ -d *.tiles ]; then exit; fi;
+	module load ndpitools;
+	module load slideToolkit;
+	mkdir -pv magick-tmp
+	export MAGICK_TMPDIR=$(pwd)/magick-tmp
+	export TMPDIR=$(pwd)/magick-tmp
 
+	if [ -f *.ndpi ]; then
+		echo \"The image-file is a NDPI and will be converted to .tif before tiling.\"
+		slide2Tiles --layer 0 -f *x40*.tif -m *emask.png;
+	
+	elif [ -f *.tif ]; then
+		echo \"The image-file was NDPI and converted to .tif.\"
+		slide2Tiles --layer 0 -f *.tif -m *.emask.png;
+	
+	elif [ -f *.TIF ]; then
+		echo \"The image-file is a .TIF.\"
+		slide2Tiles --layer 3 -f *.TIF -m *.emask.png;
+	
+	else
+		echoerrorflash \"*** ERROR *** Something is rotten in the City of Gotham; most likely a typo. Double back, please. 
+		[image-extension not recognized, should be 'ndpi', 'tif' or 'TIF' ]\"	
+		exit 1 
+	fi
+	rm -rfv magick-tmp
+	" | qsub -cwd -N ${THIS_SLIDE2TILES} -e ${PROJECTDIR}/errors/ -o ${PROJECTDIR}/logs/ -hold_jid ${THIS_SLIDEMASK} -l h_vmem=${QJOB_MEM_SLIDE2TILES} -l h_rt=${QJOB_TIME_SLIDE2TILES} -m ${MAILSETTING} -M ${EMAIL}
 
 	### slideNormalize
 	echo ""
 	echoitalic "* slideNormalize for normalization of images."
 	
-	JOB_ID_THIS_SLIDENORMALIZE=$(sbatch -J ${THIS_SLIDENORMALIZE} -e ${PROJECTDIR}/errors/slidenormalize.errors -o ${PROJECTDIR}/logs/slidenormalize.log  --mem=${QJOB_MEM_SLIDENORM} --time=${QJOB_TIME_SLIDENORM} --mail-type=${MAILSETTING} --mail-user=${EMAIL} --depend=afterany:$JOB_ID_THIS_SLIDE2TILES --parsable ${TESTDIR}/slideQuantify_normalizing.sh)
-	
-
+	echo "if [ -s files2cp.txt ]; then exit; fi;
+	if [ ! -d *.tiles ]; then
+		(>&2 echo "*** ERROR *** No tiles to process. ")
+		exit; 
+	fi
+	cd *.tiles/;
+	module load slideNormalize;
+	module load slideToolkit;
+	mkdir -pv magick-tmp
+		export MAGICK_TMPDIR=$(pwd)/magick-tmp
+		export TMPDIR=$(pwd)/magick-tmp
+	for f in *.png; do
+		echo \"...Processing tile \$f\";
+		slideNormalize \$f;
+		slideEMask -c -f \$f -t $ENTROPY_THRESHOLD
+		rm -v \$f;
+	done
+	rm -rfv magick-tmp
+	cd ..
+	ls -d -1 \$PWD/*tiles/*normalized* > files2cp.txt;
+	ls -d -1 \$PWD/*tiles/ENTROPY* >> files2cp.txt;
+	" | qsub -cwd -N ${THIS_SLIDENORMALIZE} -e ${PROJECTDIR}/errors/ -o ${PROJECTDIR}/logs/ -hold_jid ${THIS_SLIDE2TILES} -l h_vmem=${QJOB_MEM_SLIDENORM} -l h_rt=${QJOB_TIME_SLIDENORM} -m ${MAILSETTING} -M ${EMAIL}
 
 	### CellProfiler
 	echo ""
 	echoitalic "* CellProfiler to analyze images."
 	
-	JOB_ID_THIS_CELLPROFILER=$(sbatch -J ${THIS_CELLPROFILER} -e ${PROJECTDIR}/errors/cellprofiler.errors -o ${PROJECTDIR}/logs/cellprofiler.log --mem=${QJOB_MEM_CP} --time=${QJOB_TIME_CP} --mail-type=${MAILSETTING} --mail-user=${EMAIL} --depend=afterany:$JOB_ID_THIS_SLIDENORMALIZE --parsable ${TESTDIR}/slideQuantify_cellprofiler.sh)
-	
+	echo "if [ -d cp_output ]; then exit; fi;
+	module load anaconda
+	mkdir -pv cp_output
+	cellprofiler -c -r -p $PIPELINE --file-list files2cp.txt -o cp_output/;
+	" | qsub -cwd -N ${THIS_CELLPROFILER} -e ${PROJECTDIR}/errors/ -o ${PROJECTDIR}/logs/ -hold_jid ${THIS_SLIDENORMALIZE} -l h_vmem=${QJOB_MEM_CP} -l h_rt=${QJOB_TIME_CP} -m ${MAILSETTING} -M ${EMAIL}
+
 	### REMOVE THIS BREAK FOR PRODUCTION!
 	### When this break is active, only the first item 
 	### in the list of items to be processed will be processed.
@@ -245,8 +310,32 @@ else
 	echo ""
 	echoitalic "* WrapUp the work we have done, and clean house."
 	
-	JOB_ID_THIS_WRAPUP=$(sbatch -J ${THIS_WRAPUP} -e ${PROJECTDIR}/errors/wrapup.errors -o ${PROJECTDIR}/logs/wrapip.log --mail-type=${MAILSETTING} --mail-user=${EMAIL} --parsable --depend=afterany:$JOB_ID_THIS_CELLPROFILER ${TESTDIR}/slideQuantify_wrapup.sh )
+	# Obsolete code
+	# 1. we randomly grap 10 masked & tiled PNG-files to keep for post-analysis check >> OUT-COMMENTED
+	# 2. we get the data (in STAIN_Image.txt) for each study number (SLIDE_NUM) in 'cp_output' using >> OUT-COMMENTED
+	#    Colsums.R
+	# 3. we remove tiles, and other files we don't need
 	
+	echo "
+	ls cp_output/*.png | shuf -n \$(expr \$(ls cp_output/*.png | wc -l) - 10) | xargs rm;
+	echo 'SLIDE_NUM $STAIN' > results.txt;
+	cd cp_output;
+	SLIDE_NUM=\$(basename \"$PWD\") | cut -d'.' -f1
+	echo $SLIDE_NUM \$(Rscript $SLIDETOOLKITDIR/utilities/Colsums.R $STAIN $OUTPUTFILENAME) >> ../results.txt;
+	cd ..
+	rm -rfv *tiles/;
+	if [ -f *.ndpi ]; then 
+		echo \"Removing intermediate tif- & png-files converted from NDPI-files.\";
+		rm -v *x40*.tif; 
+		rm -v *x40*.png; 
+		fi;
+		echo \"Removing list of files to process.\";
+		rm -v files2cp.txt;
+		echo \"Gzipping result files.\";
+		gzip -vf cp_output/${STAIN}*.gct;
+		gzip -vf cp_output/${STAIN}*.csv;
+	" | qsub -cwd -N ${THIS_WRAPUP} -e ${PROJECTDIR}/errors/ -o ${PROJECTDIR}/logs/ -hold_jid ${THIS_CELLPROFILER} -m ${MAILSETTING} -M ${EMAIL}
+
 		cd ..
 
 		INDEX=$((INDEX+1))
@@ -260,5 +349,3 @@ else
 fi
 
 script_copyright_message
-
-
